sul-dlss/common-accessioning

- config/schedule.rb
By default, the whenever gem only deploys to servers with the :db role.  Based on the config/environments/[environment].rb, the cron is only being pushed to the first server in the list.  To rectify the problem, I'm updating the cron to push to all servers that get the :app role
> Update whenever gem roles for verify cron

- config/schedule.rb
we only want the embargo release cron to run on one machine, not all of them.
> update embargo release cron

- config/deploy/dev.rb
- config/deploy/production.rb
- config/deploy/staging.rb
somewhere along the line
```
set :whenever_roles, [:db, :app]
```
was removed from from the cap deploy files.  unfortunately, this meant that only servers with the db role were getting updates to their crons.  fixing this so crons are deployed appropriated
> add in whenever roles

- Gemfile
- Gemfile.lock
Also remove ruby 1.9 references.
Merge now, deploy when new index and OPS are ready.
Fixes #39
> Bump dor-services version and unpin rspec

- Gemfile.lock
This PR upgrades common-accessioning (the version in production on `2.x-stable`) to `dor-services` 4.23.0, which has the `externalFile` code in the publish robot.
This PR does _not_ need to be cherry-picked into `master`.
> upgrade dor-services to 4.23.0

- config/deploy.rb
- config/deploy/production.rb
This PR provides for deploying a specific branch to production, and deploys to robots1-5. @blalbrit can you please review? It looks like Rosy has common-accessioning running on all robots1-5...
> Cap deploy fixes

- bin/fix_xsums.rb
- bin/repub
- integration_tests/versioning/versioning_spec.rb
- lib/dor/accession_lite.rb
- robots/accession/abstract_metadata.rb
- robots/accession/embargo_release.rb
- robots/accession/end_accession.rb
- robots/accession/provenance_metadata.rb
- robots/accession/publish.rb
- robots/accession/remediate_object.rb
- robots/accession/reset_workspace.rb
- robots/accession/sdr_ingest_transfer.rb
- robots/accession/shelve.rb
This PR fixes #75 and is in preparation to use ActiveFedora 7 which will throw exceptions on type mismatches (i.e., using `Dor::Item.find` for a `Dor::Collection` object).
> switch from Dor::Item.find to Dor.find when object type is unknown a priori

- Gemfile
- Gemfile.lock
by using dor-services v5.29.0, common-accessioning robot `sdr-ingest-transfer` will kick off preservationIngestWF instead of sdrIngestWF, thus using the new code preservation_robots instead of sdr-preservation-core.
I assert that there is functional parity;  this has been tested by manually running a test object through common accessioning and preservation robots on production.
> dor-services v5.29.0 to use new preservationIngestWF

- config/boot.rb
ActiveFedora (in our old-ass version) still expects to be able to `return false` out of a callback to skip remaining callbacks.
This buys us some time to still use rails 5.1 with ActiveFedora, but it is fleeting, since the option goes away in rails 5.2.
See: https://github.com/sul-dlss/hydrus/issues/161
> Directed at production problem related to dependency shift

- Gemfile.lock
8.5.0 is compatible with Rails 5, which we need here or the `return false` strategy in callbacks fails to break callback chain.
> Bump active-fedora version

- Gemfile
- Gemfile.lock
Reverts part of https://github.com/sul-dlss/common-accessioning/commit/bb25acf282b006b394b850943cdb05aa5e65102a
The issue was resolved: https://github.com/lostisland/faraday/pull/619
> Upgrade to net-http-persistent 3

- Gemfile
- Gemfile.lock
Updates to the latest 6.x version of dor-services to fix the preservable issue of collections.
> Update dor-services version to 6.0.5

- Gemfile.lock
This has a fix for `undefined method 'dsid' for nil:NilClass`
> Update to dor-services 6.1.9

- config/environments/test.rb
- lib/dor/item.rb
update-marc step in item-release fails since it is using a misconfigured dor-services-url, fix and update local test.rb config to match latest style.
> update to use new dor services url location in config

- spec/robots/accession/remediate_object_spec.rb
The warning was:
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives
> Refactor spec to avoid a warning about not expecting an exception

- lib/datastream_builder.rb
- robots/accession/content_metadata.rb
- robots/accession/descriptive_metadata.rb
- robots/accession/provenance_metadata.rb
- robots/accession/rights_metadata.rb
- robots/accession/technical_metadata.rb
- spec/lib/datastream_builder_spec.rb
This makes it easier to understand what methods are being called
because it elminiates metaprogramming.
> Pass explicit blocks to DatastreamBuilder

- spec/spec_helper.rb
> Don't stub publish_metadata.

- lib/sdr_ingest_service.rb
- spec/lib/sdr_ingest_service_spec.rb
It's easier to understand what is happening if you don't need to look
in different codebases.
> Move datastream requirements from shared-configs to code

- lib/dor/release/item.rb
- robots/dor_repo/release/release_members.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/release/release_members_spec.rb
This avoids a number of deprecated methods and APIs
> Create the releaseWF by name

- config/deploy/prod.rb
currently they are deployed to all machines, which is what used to happen as etds were only deployed on one machine
> Only run crons on one machine

- config/deploy/prod.rb
- config/deploy/stage.rb
Otherwise deploys don't get reported
> Honeybadger expects app or the honeybadger_server to be set

- robots/dor_repo/assembly/accessioning_initiate.rb
We are seeing situations where the headers are never sent to dor-services-app,
I'm hoping to log when that situation happens so we can better troubleshoot
> Log when auth is missing

- lib/technical_metadata_service.rb
We manage this in the Gemfile, so it would be impossible for it not to exist at this point
> remove test for jhove service

- lib/dor/etd/rights_metadata_generator.rb
- lib/models/etd_metadata.rb
- spec/lib/dor/etd/rights_metadata_generator_spec.rb
The get_embargo_date was deprecated and then removed, but since there was no
test coverage, we never saw the deprecation
Fixes #312
> Switch to use the new etd_embargo_date method

- config/settings.yml
Per the goobi outage post-mortem, we decided to move away from using `example.com` as a test hostname as it can resolve and return unexpected 404 errors during tests. 
This replaces `example.com` with `dor-services-test.stanford.test`.
* The `.test` TLD is specifically setup for testing and not be resolvable (https://en.wikipedia.org/wiki/.test)
* By using the same url structure we see in prod but with `-test` it may be easier to debug production configurations by having easy access to the proper url structure here.
> Change test config URL to a non resolvable host

- robots/dor_repo/accession/end_accession.rb
- spec/robots/accession/end_accession_spec.rb
Previously we were getting a NoMethodError here.  This adds a test so we don't
run into such a problem again.
Fixes #324
> Allow was-dissemniation workflow to be kicked off

- lib/robots/dor_repo/accession/embargo_release.rb
- spec/robots/accession/embargo_release_spec.rb
embargo script rescue block currently explodes and stops the script because we are trying to set a workflowstep that doesn't exist anymore -- just use an HB notification instead
> do not set error status for a workflow step that does not exist

- lib/robots/dor_repo/accession/embargo_release.rb
- spec/robots/accession/embargo_release_spec.rb
There are some objects that have passed embargo but were not never accessioned (test objects or orphaned).  Right now this generates an exception which gets honeybadgered each day, which seems excessive (unless and until we clean these ones up and don't generate more).  This code simple logs these cases instead of trying to release and then generate an exception.
> do not generate errors for non-accessioned objects when releasing

- lib/dor/assembly/stub_content_metadata_parser.rb
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
ported from https://github.com/sul-dlss-deprecated/assembly/pull/66
This is a pre-req for the actual content metadata generation which occurs here: https://github.com/sul-dlss/assembly-objectfile/pull/7
> allow 3d content type to pass through from stub content metadata

- Gemfile
- Gemfile.lock
We haven't seen that 4.1.0 helps resolve timeout errors
> Revert pinning redis

- lib/datastream_builder.rb
- lib/robots/dor_repo/accession/embargo_release.rb
- lib/robots/dor_repo/etd_submit/check_marc.rb
- lib/technical_metadata_service.rb
- spec/lib/datastream_builder_spec.rb
- spec/lib/technical_metadata_service_spec.rb
- spec/robots/accession/embargo_release_spec.rb
- spec/robots/etd_submit/check_marc_spec.rb
raise error and/or notify Honeybadger and log error if a fedora save doesn't work.
Ran into this oversight while working on #372 (descMetadata must have required fields.)
This PR isn't perfect, but I think it should be merged if you believe it represents an improvement over what currently exists in the code and if you don't see any blockers.
Closes #377 (not user facing, so can autoclose with merge)
> raise error and/or notify Honeybadger and log error if a fedora save doesn't work.

- lib/datastream_builder.rb
- lib/dor/assembly/content_metadata.rb
- lib/robots/dor_repo/accession/descriptive_metadata.rb
- lib/robots/dor_repo/assembly/content_metadata_create.rb
- lib/robots/dor_repo/etd_submit/binder_batch_transfer.rb
- lib/robots/dor_repo/etd_submit/other_metadata.rb
- lib/sdr_ingest_service.rb
- spec/lib/sdr_ingest_service_spec.rb
- spec/robots/accession/descriptive_metadata_spec.rb
- spec/robots/assembly/content_metadata_create_spec.rb
This PR is motivated from First Responder duties:  looking at some errors in honeybadger that don't have a druid included.
I can't think of any downstream consumers of these error messages that would be negatively impacted ...
> improve error messages

- lib/robots/dor_repo/accession/embargo_release.rb
- spec/robots/accession/embargo_release_spec.rb
This prevents an exception that occurs when opening an object that is already open
Fixes #388
> Don't try to do embargo release on an open object

- lib/datastream_builder.rb
- lib/robots/dor_repo/accession/descriptive_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
Fixes #393 
related to #386, and may fix that as well
We have been getting this error but inappropriately -- the descMetadata is there and it has a title:
I was able to reproduce the error in stage consistently by registering an object with a catkey and no label, and then adding the accessioningWF.
This PR fixes the problem by reloading the Dor object before checking for required fields in a possibly newly updated datastream.
I deployed the fix to stage and empirically established that the fix works.
> FIX BUG:  desc metadata required fields check

- lib/robots/dor_repo/accession/descriptive_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
took @mjgiarlo's excellent refactoring suggestion on PR #394
> descriptive_metadata: refactor: use obj.reload instead of Dor.find

- config/boot.rb
This is required so that we can use `Settings` in the environment files (e.g. `config/environments/production.rb`)
> Load environment settings after the config

- Gemfile.lock
- spec/fixtures/workspace/dd/116/zh/0343/dd116zh0343/metadata/technicalMetadata.xml
- spec/fixtures/workspace/jq/937/jp/0017/jq937jp0017/metadata/technicalMetadata.xml
This branch is now deployed to stage. Would like @andrewjbtw to toss a new object up (that has the buildSubtree problem in prod, such as https://argo.stanford.edu/view/druid:cm855qk5101) and confirm that this works OK before making it a real PR and pushing to prod.
> Bump jhove-service to 1.3.0 to pick up JHOVE 1.22.x for testing in stage

- config/deploy.rb
To avoid worker downtime during deployment
Used in preservation_robots successfully for a while now
> Replace resque:pool:full_restart with hot_swap

- spec/robots/assembly/jp2_create_spec.rb
Prior to this change this sequence would cause a failure:
```
rspec spec/robots/assembly/jp2_create_spec.rb:227 spec/robots/assembly/jp2_create_spec.rb:321 --seed 54373
```
> Fix random spec.

- lib/dor/assembly/item.rb
Having dead code lying around is confusing.
n/a
> Prune dead code

- lib/robots/dor_repo/accession/remediate_object.rb
- spec/robots/accession/remediate_object_spec.rb
The method this is calling was removed 3 years ago:
https://github.com/sul-dlss/dor-services/pull/260/files#diff-a42b00f2db1198c23e44cdfc6ed95658L58
> Make the remediate step a no-op

- spec/robots/assembly/jp2_create_spec.rb
Prior to this change, a test failure could be triggered by running:
```
rspec spec/robots/assembly/jp2_create_spec.rb[1:2:1:1,1:2:4:2:1] --seed 15263
```
n/a
> Fix a flapping spec

- lib/robots/dor_repo/accession/shelve.rb
Some shelving operations, namely web-archiving take a long time.
n/a
> Update the timeout to 30 minutes for shelving

- lib/dor/assembly/item.rb
- lib/robots/dor_repo/assembly/base.rb
- spec/robots/assembly/accessioning_initiate_spec.rb
- spec/robots/assembly/checksum_compute_spec.rb
- spec/robots/assembly/jp2_create_spec.rb
- spec/spec_helper.rb
This reverts commit aefba29f681438e73066343d2413fccefc46f540. Because the code wasn't dead, it just wasn't covered by tests.  Added tests that cover it.
N/a
> Revert "Prune Dead Code"

- lib/robots/dor_repo/accession/shelve.rb
To accommodate long jobs without having timeouts.
n/a
> Increase the timeout for shelve jobs

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/publish.rb
- spec/robots/accession/publish_spec.rb
Publish jobs were made asynchronous as they were timing out. We should wait for them to complete.
n/a
> Wait for publish jobs to finish

- lib/robots/dor_repo/accession/publish.rb
- lib/robots/dor_repo/accession/shelve.rb
- spec/robots/accession/publish_spec.rb
- spec/robots/accession/shelve_spec.rb
The polling operations can timeout and are not possible to reset using argo.
Depends on https://github.com/sul-dlss/dor-services-app/pull/490
and https://github.com/sul-dlss/workflow-server-rails/pull/271
n/a
> [Need PO approval] Allow dor-services-app to use callbacks rather than polling

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/publish.rb
- lib/robots/dor_repo/release/release_publish.rb
So the api call knows which workflow to callback to.
n/a
> Report which workflow the callback for publish should report to

- lib/datastream_builder.rb
- spec/lib/datastream_builder_spec.rb
This code was unused and having unused code paths makes it harder to maintain.
n/a
> Remove an unused argument

- lib/robots/dor_repo/accession/content_metadata.rb
- spec/robots/accession/content_metadata_spec.rb
This has no effect when the block passed to build is empty.
N/A.
> Remove force flag for contentMetadata

- lib/datastream_builder.rb
- lib/robots/dor_repo/accession/content_metadata.rb
- lib/robots/dor_repo/accession/descriptive_metadata.rb
- lib/robots/dor_repo/accession/rights_metadata.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/datastream_builder_spec.rb
- spec/robots/accession/content_metadata_spec.rb
- spec/robots/accession/descriptive_metadata_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
There's no need to pass object as an argument, the datastream object has all the information this class needs.
n/a
> Remove unnecessary object parameter from DatastreamBuilder

- lib/robots/dor_repo/etd_submit/binder_batch_transfer.rb
- lib/robots/dor_repo/etd_submit/catalog_status.rb
- spec/robots/etd_submit/catalog_status_spec.rb
These methods are deprecated, so we should use the preferred methods instead.
n/a
> Use the non-deprecated workflow methods

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/descriptive_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
This decouples the robot from Fedora and switches to an API based interface.
n/a
> Update descMetadata using an API

- lib/dor/assembly/content_metadata.rb
- lib/dor/assembly/item.rb
- lib/dor/assembly/path_finder.rb
- lib/robots/dor_repo/assembly/accessioning_initiate.rb
- lib/robots/dor_repo/assembly/checksum_compute.rb
- spec/robots/assembly/jp2_create_spec.rb
There is no reason to have a module that is only used once. Make it a class instead
n/a
> Extract PathFinder from Assembly::Item

- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
When we are accessioning an object for the first time, there is no technicalMetadata.  We need to handle this case properly.
Fixes https://app.honeybadger.io/projects/52894/faults/58394059
n/a
> TechnicalMetadataService copes with no technical metadata from preservation

- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
b/c I goofed in the previous PR #472 to fix https://app.honeybadger.io/projects/52894/faults/58394059.
I believe the real problem was that the regex didn't accommodate multiple lines;  it is also a bit worrying that the exception from pres-client isn't a NotFound, but I have a diff ticket for that.
n/a
> TechnicalMetadataService copes PROPERLY with no technical metadata from preservation

- Gemfile.lock
- lib/technical_metadata_service.rb
preservation-client v1.0.0 throws a Preservation::Client::NotFoundError when an API call to preservation-catalog returns 404.  This simplifies code here that traps for that error.
n/a
> preservation-client v1.0.0 to get technicalMetadata.xml

- lib/robots/dor_repo/accession/content_metadata.rb
- spec/robots/accession/content_metadata_spec.rb
This decouples the robot from Fedora and switches to an API based interface.
n/a
> Update contentMetadata using an API

- lib/dor/assembly/item.rb
- spec/robots/assembly/accessioning_initiate_spec.rb
- spec/robots/assembly/checksum_compute_spec.rb
- spec/robots/assembly/jp2_create_spec.rb
- spec/spec_helper.rb
We want to keep common-accessioning from accessing fedora so we can replace it.
n/a
> Do assembly without hitting Fedora (directly)

- lib/dor/release/item.rb
- lib/robots/dor_repo/release/update_marc.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/release/update_marc_spec.rb
Removes unnecessary indirection on how the update_marc code is called.
n/a
> Refactor to put the updating marc code close to where it is used

- lib/dor/release/item.rb
- lib/dor/release/member_service.rb
- lib/robots/dor_repo/release/release_members.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/release/release_members_spec.rb
- spec/robots/release/release_publish_spec.rb
- spec/spec_helper.rb
A class should have a single responsibility.  The Release::Item class had several responsibilities, this extracts the responsibility for finding collection members to its own class
n/a
> Extract a member service from Release::Item

- .rubocop_todo.yml
- lib/robots/dor_repo/assembly/jp2_create.rb
- spec/lib/technical_metadata_service_spec.rb
> Correct space around operators

- .rubocop_todo.yml
- spec/spec_helper.rb
> Remove useless assignment

- lib/robots/dor_repo/accession/publish.rb
- spec/robots/accession/publish_spec.rb
closes #1768
To allow APOs to proceed with AccessionWF without invoking publish.
No
> Marks publish-complete to completed for APOs.

- Gemfile
- Gemfile.lock
- spec/lib/technical_metadata_service_spec.rb
The latest version of JHOVE-service has a performance improvement for processing XTML files.
No.
> Upgraded JHOVE Service to 1.4.0 (for XHTML fix for Google Books).

- Gemfile
- Gemfile.lock
- config/boot.rb
- config/settings.yml
HOLD until: 
pres cat will start requiring that all API clients supply an auth token, or their requests will be rejected as Unauthorized.
Fixes #502
connects to sul-dlss/preservation_catalog#1298
blocks sul-dlss/preservation_catalog#1306
n/a
> pass auth token to pres-client

- lib/dor/assembly/file_node.rb
- lib/dor/assembly/image_data_node.rb
- lib/robots/dor_repo/assembly/exif_collect.rb
- spec/lib/dor/assembly/image_data_node_spec.rb
- spec/robots/assembly/exif_collect_spec.rb
This represents a unique concept that is separate from the ExifCollect robot
n/a
> Extract file and image node classes from exif_collect

- spec/lib/dor/release/item_spec.rb
Having unnecessary stubs is confusing 
n/a
> Remove unused stub

- Gemfile
- Gemfile.lock
So that robots will start reporting the started status.
No.
> Upgrades lyber-core to 5.5

- lib/dor/assembly/content_metadata.rb
- lib/dor/assembly/item.rb
- lib/dor/assembly/stub_content_metadata_parser.rb
- spec/robots/assembly/jp2_create_spec.rb
Reorganize stub content metadata methods into StubContentMetadataParser
Tests should use stubs instead of writers.  This helps tease appart the files for stub contentMetadata vs regular contentMetadata
> Remove unused writers

- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
So that notifications are not sent when a content directory is empty. An empty content directory indicates a metadata only update.
No
> Tweak to experiment to ignore empty content dirs.

- lib/datastream_builder.rb
rightsMetadata has been show to be added as a file in certain cases.  contentMetdata no longer uses this class
n/a
> Update experiment to show current assumptions

- lib/dor/release/item.rb
- lib/robots/dor_repo/release/release_members.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/release/release_members_spec.rb
- spec/spec_helper.rb
This avoids a call to Fedora
n/a
> Use the cocina endpoint to determine object_type

- lib/robots/dor_repo/accession/technical_metadata.rb
- lib/technical_metadata_service.rb
- spec/lib/datastream_builder_spec.rb
- spec/lib/technical_metadata_service_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
Instead use the API methods. This positions the project to remove the Fedora dependency
n/a
> Refactor the technical metadata robot not to use DatastreamBuilder

- lib/robots/dor_repo/accession/rights_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
- spec/robots/accession/rights_metadata_spec.rb
We're trying to move to using the API methods for updating metadata rather than directly communicating with Fedora
n/a
> Refactor RightsMetadata robot to not depend on DatastreamBuilder

- lib/robots/dor_repo/accession/technical_metadata.rb
- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
This removes the TechnicalMetadataService's dependency on Fedora
n/a
> Do dependency injection for TechnicalMetadataService

- lib/technical_metadata_service.rb
This was originally here: https://github.com/sul-dlss/dor-services/blob/9e72fb39facf55fa84d0de6348000b2cd4932b4a/lib/dor/models/concerns/itemizable.rb#L34
Which was copied to here: https://github.com/sul-dlss/dor-services/commit/9e72fb39facf55fa84d0de6348000b2cd4932b4a#diff-7eb9eefd909d64459102b2c923082a19R37
and eventually made it's way into common-accessioning.  However, this no longer seems to serve any purpose if it ever did.
n/a
> Remove unnecessary check

- lib/dor/assembly/item.rb
- lib/robots/dor_repo/accession/content_metadata.rb
- lib/robots/dor_repo/accession/publish.rb
- lib/robots/dor_repo/accession/shelve.rb
- lib/robots/dor_repo/release/release_members.rb
- spec/robots/accession/shelve_spec.rb
- spec/robots/release/release_members_spec.rb
These methods are available as of cocina-models 0.9.0. This is a refactoring and thus should not need test changes. As part of this work, improve code comments.
Code comments, yes.
> Prefer model type-checking methods over `#is_a?`

- lib/robots/dor_repo/accession/rights_metadata.rb
- spec/robots/accession/rights_metadata_spec.rb
This decouples common-accessioning from Fedora
n/a
> Remove a Dor.find from rightsMetadata in favor of the cocina api

- lib/robots/dor_repo/accession/rights_metadata.rb
This makes the code easier to read
n/a
> Refactor to avoid shadowing variables

- lib/robots/dor_repo/accession/end_accession.rb
- spec/robots/accession/end_accession_spec.rb
We are trying to remove the calls to Fedora 3
n/a
> Refactor end-accession robot to use cocina api rather than Fedora

- lib/robots/dor_repo/release/release_members.rb
Because `@druid` can be undefined. I believe this will fix https://github.com/sul-dlss/argo/issues/1796
no
> Use passed-in druid in ReleaseMembers robot

- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
This gives more descriptive names to methods and makes the logic simpler
n/a
> Refactor technical_metadata_service

- Gemfile.lock
Upgrade to latest lyber-core (which contains additional HB reporting).
No
> Updated lyber-core.

- README.md
- bin/run_robot
- bin/run_robot_cron
- config/schedule.rb
It's deprecated because it's a lot more indirection than is required
> Avoid LyberCore::Robot.step_to_classname

- lib/robots/dor_repo/accession/rights_metadata.rb
- spec/robots/accession/rights_metadata_spec.rb
The experiment proved this path was never called.
Fixes #652
n/a
> Removed a dead code path

- config/settings.yml
- lib/dor/release/member_service.rb
- lib/robots/dor_repo/goobi/goobi_notify.rb
- lib/robots/dor_repo/release/release_members.rb
- lib/robots/dor_repo/release/update_marc.rb
Furthermore the robots are intended to be restarted if there is an error.
n/a
> The clients have faraday retry logic built in already

- .travis.yml
This reflects the currently deployed ruby version.
n/a
> Update the tested ruby versions

- Gemfile
- Gemfile.lock
This will allow ruby 2.7 compatibility
n/a
> Update the config gem

- lib/models/etd_metadata.rb
- lib/robots/dor_repo/etd_submit/other_metadata.rb
- spec/models/etd_spec.rb
- spec/robots/etd_submit/other_metadata_spec.rb
It doesn't belong on the model as it's business logic and it's only used in one place
Ref #582 
n/a
> [Refactor] move populate_datastream to the robot where it is used

- config/environments/production.rb
- config/settings.yml
To remove unnecessary configuration.
No.
> Removed local_workspace_root

- Gemfile
- Gemfile.lock
- README.md
Our last code coverage data was from Jan 31, 2020.
updated badge on README
n/a
If so, please confirm:
> fix coveralls hookup

- bin/run_robot_cron
- lib/etd_submit/robot_cron_base.rb
The change to lyber-core 6 made the cron suddenly stop working with no output.
1. count the number of processes running correctly
2. removed repo parameter
3. renamed step_name to process
n/a
If so, please confirm:
> Fix the robot cron for changes in lyber-core 6

- bin/run_robot_cron
Add a simple timestamp to the `crondebug.log` output to assist in debugging.
> Add a timestamp to crondebug.log

- bin/run_robot_cron
Fixes #600 
This is a quick fix for running the etd crons. A more idiomatic approach will be to write a lock or pid file for the process
> Remove the run_robot_cron command from the grep output

- lib/robots/dor_repo/etd_submit/check_marc.rb
> WAITING is no longer a method

- lib/robots/dor_repo/etd_submit/other_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
- spec/robots/accession/provenance_metadata_spec.rb
- spec/robots/accession/rights_metadata_spec.rb
- spec/robots/etd_submit/other_metadata_spec.rb
After getting a catkey (check_marc), we need to generate the descMetadata for ETDs.  Previously this was in the accessionWF, but this was removed as we didn't think anything used it.  Howeveer it appears that ETDs were depending on it..
n/a
n/a
> Generate descriptive metadata for etds

- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/robots/accession/technical_metadata_spec.rb
Fixes #608
we only want to generate techMd for preserved files.
n/a
not yet.  :-)
> accessioningWF: only generate techMd for preserved files

- spec/robots/accession/technical_metadata_spec.rb
Closes #610
To remove unnecessary tests.  The default behavior of a cocina-model is determined in the cocina-model gem.
na
na
> shorten techmd spec, as default sdrPreserve is set by cocina-models

- lib/dor/etd/content_metadata_generator.rb
The ETDs never set `properties.label`.  So these are always nil.
Fixes #614
n/a
> Stop making empty nodes in contentMetadata for ETDs

- spec/robots/accession/end_accession_spec.rb
- spec/robots/assembly/exif_collect_spec.rb
we don't depend on these stubs anymore.
n/a
no
> Remove unnecessary stubs

- config/settings.yml
- config/settings/test.yml
- lib/robots/dor_repo/etd_submit/build_symphony_marc.rb
- lib/robots/dor_repo/etd_submit/submit_marc.rb
- spec/robots/etd_submit/submit_marc_spec.rb
Fixes #616 
Corresponding shared_configs updates have been applied.
N/A
No.
> Use mounted /dor/workspace/etdSubmitWF path for sumit marc generation

- .travis.yml
Test on the latest version. No need to allow failures anymore
no
no
> Update tests for latest ruby

- Gemfile
- Gemfile.lock
> Upgrade simplecov to 0.18.5

- lib/file_uri.rb
- lib/file_uris.rb
- spec/lib/file_uris_spec.rb
> Properly escape diacritics in file uris

- config/deploy.rb
Fixes #641
Should restore ability to record deployments via Honeybadger
No
No
> Set honeybadger_server in capistrano configuration

- config/deploy/prod.rb
- config/deploy/stage.rb
This setting was overriding the one set in config/deploy.rb.
HB deployments were broken in https://github.com/sul-dlss/common-accessioning/pull/622 when the `:cron` capistrano role was removed.
> Remove env-specific honeybadger servers

- lib/preserved_file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/file_uri_spec.rb
- spec/lib/preserved_file_uris_spec.rb
> Only generate technical metadata for preserved files

- lib/robots/dor_repo/accession/technical_metadata.rb
- lib/robots/dor_repo/base.rb
- spec/robots/accession/technical_metadata_spec.rb
refs https://github.com/sul-dlss/technical-metadata-service/issues/129
To pass the lane-id to techmd service to support prioritization.
No.
Yes.
> Adds prioritization when requesting techmd.

- bin/run_robot
same change as sul-dlss/preservation_robots#222
the `#work` method in the robot now requires a context to be passed in for reporting to honeybadger, so the run_robot script needs to ~~pass in an extra parameter in the method call to work~~ call the `#perform` method instead, which takes care of the optional parameter
see https://github.com/sul-dlss/lyber-core/blob/master/lib/lyber_core/robot.rb#L40
not needed
no
> allow run_robot to work

- lib/robots/dor_repo/accession/publish.rb
- lib/robots/dor_repo/accession/shelve.rb
- spec/robots/accession/publish_spec.rb
- spec/robots/accession/shelve_spec.rb
We can now use 'noop' and have dor-services-app set these steps to complete. This follows what we're doing in the technical metadata step
Ref https://github.com/sul-dlss/argo/issues/1789
Ref https://github.com/sul-dlss/dor-services-app/pull/850
Ref https://github.com/sul-dlss/workflow-server-rails/pull/377
no
Yes. Was tested on stage.
> Remove *-complete steps from accession WF

- lib/robots/dor_repo/release/release_publish.rb
- spec/robots/release/release_publish_spec.rb
This prevents the release-publish step from being set to complete until the api is done. This step gets updated by dor-services-app in PublishJob
> Noop the release publish

- lib/robots/dor_repo/accession/sdr_ingest_transfer.rb
- spec/robots/accession/sdr_ingest_transfer_spec.rb
This step is completed by dor-services-app
Part of sul-dlss/argo#1789
integration test on stage.
n/a
> Return no-op from sdr_ingest_transfer

- lib/robots/dor_repo/accession/content_metadata.rb
- spec/robots/accession/content_metadata_spec.rb
This aligns the content-metadata robot with the way the rights-metadata and desc-metadata robots work.  It allows the users to see when this functionality is used and when it isn't.
tested locally
none
> When there is no contentMetadata.xml mark the step as skipped

- config/environments/production.rb
b/c cruft makes maintenance harder
we stopped using jhove when we switch to techmd-service
checked and no jhove setting in shared_configs.
> remove unused jhove setting

- spec/lib/dor/release/member_services_spec.rb
~~(continues to) fixes sul-dlss/argo#2243~~
~~Basically we still have an issue with identifying members of a collection.  Object type is in a multivalued solr field, so that when dor-services-client parses this result from dor-services app here: https://github.com/sul-dlss/dor-services-client/blob/master/lib/dor/services/client/members.rb it makes the `type` an array in the response, and not a string. Thus, determining if a member is an item or a collection needs to be done assuming this value is an array, else you will always get an empty set when asking for items or collections regardless of how many members are returned.  We also need to guard against a nil type, as this may occur in some solr documents.~~
Add a new test for a class that had no test before.
Also see …
> add a test for member service

- lib/robots/dor_repo/accession/shelve.rb
- spec/robots/accession/shelve_spec.rb
Even if there are no files present. The deaccession use case depends on shelve being called with no files, which causes stacks to remove the files.
Fixes #715
> Always run the shelve step

- Gemfile
- Gemfile.lock
The new version of assembly-objectfile supports the new webarchive-seed content metadata generation.
> bump version of assembly-objectfile

- Gemfile.lock
deleted `Gemfile.lock` and re-ran `bundle install` locally.
fix the following deployment error:
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
The dependencies in your gemfile changed
You have added to the Gemfile:
* dor-services-client (~> 6.30)
You have deleted from the Gemfile:
* dor-services-client (~> 6.27)
1: from /Users/suntzu/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/suntzu/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as …
```
> bundle install to try to fix out of sync Gemfile.lock

- Gemfile.lock
skip updating assembly-objectfile, since that broke the build
get to the latest cocina-models, without breaking the build (see #744).
```diff
common-accessioning % git diff upd-deps-again upd-some-deps-again                      upd-some-deps-again
diff --git a/Gemfile.lock b/Gemfile.lock
index c690d8b..c8b1a53 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -13,7 +13,7 @@ GEM
assembly-image (1.7.7)
assembly-objectfile (>= 1.6.4)
mini_exiftool (>= 1.6, < 3)
-    assembly-objectfile (1.10.2)
+    assembly-objectfile (1.10.1)
activesupport (>= 5.2.0)
deprecation
dry-struct (~> 1.0)
```
unit tests
n/a
> bundle update cocina-models, dor-services-client, and honeybadger

- Gemfile
- Gemfile.lock
To get the change in sul-dlss/assembly-objectfile#50 working (it sets json mimetypes correctly)
> bump assembly-objectfile gem to get json mimetypes

- config/resque-pool.yml
This is an attempt to reduce the maximum load we put on Fedora.
This is not exactly the same as the originally proposed elimination of 1 VM:  no `assemblyWF_jp2` workers are cut (still 4 total), and we cut 30% of the other workers (3/10 on each of 4 boxes) instead of 25% (10 of the 40 total).  This is a 27% reduction in overall worker count (3/11).
A possible advantage compared to the original plan is that decreasing the number of workers on each box decreases the max possible demand for simultaneous connections on each box, and the failures we're seeing are usually with an exhaustion of available outbound connections.
connects to #758
connects to sul-dlss/dor-services-app#2559
I think we're assuming that we can't reproduce this in stage, and since this is safe (worst consequence is …
> decrease the number of common-accessioning workers

- config/resque-pool.yml
we hope that this might reduce or eliminate issues with dor-services-app running out of outbound connections when talking to fedora (the hypothesis being the fedora is slow, and a backlog of requests to it will pile up as load from accessioning and/or indexing increases).
see https://github.com/sul-dlss/common-accessioning/issues/758 and https://github.com/sul-dlss/common-accessioning/pull/759/files
um...
worker allocation in resque pool config
> reduce number of accessioning workers to alleviate pressure on fedora

- lib/dor/assembly/stub_content_metadata_parser.rb
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
- spec/test_input/aa/111/bb/5555/stubContentMetadata.xml
Fixes #772 
~~[HOLD] Don't merge yet, pending some verification with actual data on stage~~  Done.
When books are accessioned via Goobi, the arrive with "stub" content metadata, which needs to be converted to content metadata during accessioning.  They will have the reading order identified in the content type, and this must be parsed correctly so we can send the reading order to our gem when generating the actual content metadata from the stub.  We recently added this new "reading_order" parameter to the content metadata generation gem, but do not currently set it when converting from stub --> content metadata during accessioning.  This fixes it.
Added tests.  Verified that it works correctly with actual stub content metadata coming from Goobi.
> pass reading order to gem when generating content metadata from stub

- config/resque-pool.yml
trying to reduce load on fedora during periods of peak demand.
per discussion on slack last friday and in standup today.
see also https://github.com/sul-dlss/common-accessioning/issues/758
😅 
resque-pool config change only
> reduce common-accessioning worker allocation by 1 per VM

- config/resque-pool.yml
per https://github.com/sul-dlss/common-accessioning/issues/758#issuecomment-899630759
continuing to experiment with fewer common-accessioning workers to try reducing pressure on fedora to prevent DSA using up all its outgoing connections due to slow fedora responses.
we'll see once deployed whether it helps alleviate connection issues when lots of accessioning activity is happening at once
resque-pool to adjust worker count
> try decreasing by one worker per VM again

- Gemfile.lock
to update dependencies (wasn't triggered by jenkins for some reason -- maybe the `openapi_parser` gem updated more recently)
> Update dependencies (manually)

- lib/robots/dor_repo/accession/rights_metadata.rb
We don't think this is used, but we'd like to confirm this by monitoring in prod
> Notify if rights-metadata robot finds xml

- lib/robots/dor_repo/accession/provenance_metadata.rb
- spec/robots/accession/provenance_metadata_spec.rb
In a meeting today, Andrew agreed this step is not useful as this data is duplicative of what is recorded in the events service.  This will reduce the load on DSA and Fedora.
> Make provenance-metadata a no op

- config/resque-pool.yml
So that no work gets picked up by techmd while we migrate it to Ubuntu
Tested in stage
N/A
> Shut down common-accessioning workers

- Gemfile
- Gemfile.lock
> simplecov no longer needs version restricted

- config/boot.rb
- lib/models/part.rb
This used to be used for ETD when we modeled part objects in Fedora
> Remove unused model

- .rubocop.yml
- .rubocop_todo.yml
- lib/dor/structural_metadata.rb
- spec/robots/accession/content_metadata_spec.rb
> Ensure that dark objects do not try to publish or shelve

- lib/dor/file_sets.rb
- spec/lib/dor/structural_metadata_spec.rb
> Citation only access on an object should create dark files

- lib/dor/structural_metadata.rb
- lib/dor/viewing_direction_helper.rb
- spec/lib/dor/structural_metadata_spec.rb
Part of #866, this will allow accessioning to continue.  Andrew has requested this change;  furthermore, he has said there is a way to fix an incorrect viewing direction.
Another PR to avoid this problem in the first place via pre-assembly is in the works.
unit tests
> if //bookData/@readingOrder is missing, don't raise exception

- config/deploy.rb
common-accessioning boxes are going to ubuntu
Part of sul-dlss/assembly-image/issues/51
> ubuntu deploy fix for resque-pool

- config/settings.yml
- lib/robots/dor_repo/assembly/jp2_create.rb
- spec/robots/assembly/jp2_create_spec.rb
This makes it easier to read the code.  We never set these to anything except 'false', so we can just hardcode the values.  See https://github.com/sul-dlss/shared_configs/blob/common-accessioning-prod/config/settings/production.yml#L11-L12
CI
> Remove unnecessary conditionals

- lib/robots/dor_repo/assembly/jp2_create.rb
We weren't seeing the messages from this path in the logs. Maybe this never happens?  If we don't see this notification in a few months, we can remove this code.
it wasn't! It's dead code 💀
> Notify about a path we think might be dead code

- config/resque-pool.yml
per https://github.com/sul-dlss/preservation_catalog/issues/1896, stanford is currently experience campus-wide networking issues as a result of an ongoing multi-day electrical power outage/reduction.  per conversation with @andrewjbtw and @julianmorley on slack yesterday, we're pausing the accessioning pipeline until power/network stability is restored.  per conversation with @ndushay and @justinlittman in standup today, we're zeroing the worker count in common-accessioning and preservation_robots, so that monday's FR (@jcoyne) doesn't have to worry about stopping resque-pool when deploying dependency updates, if the outage is still ongoing.
once network stability is restored, we should revert this change.
we've used this pattern a number of times in the past for stopping workers from …
> temporarily set worker counts to zero, to prevent accessioning

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- README.md
assembly-image v2.0.0 uses `ruby-vips` to use `libvips` for better temporary tiff and better jp2 image creation.
A branch of this code pointing to a branch of assembly-image PR sul-dlss/assembly-image/pull/65 was vetted by Andrew;  Tony Calavano vetted assembly-image code independently, too.
> use assembly-image 2.0 for better jp2 images

- config/resque-pool.yml
revert temporary stoppage related to last week's power/network outage.  see https://github.com/sul-dlss/preservation_catalog/issues/1896.
i will manually kill the resque pool master processes for common accessioning when this is deployed to prod, so that we can let pres robots work off its backlog first.  (the current plan is to let the `preservationIngestWF` backlog get worked off, before re-enabling common-accessioning robots)
reverting to original working config
> re-enable common-accessioning workers

- lib/robots/dor_repo/assembly/jp2_create.rb
Fixes #928 - note, this code path does have tests (code coverage shows them as covered and I verified via byebug it is hitting that code path).
See https://codeclimate.com/github/sul-dlss/common-accessioning/lib/robots/dor_repo/assembly/jp2_create.rb for 100% coverage report 
Also, if you have the Code Climate plugin for firefox, you'll see those lines in green at https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/assembly/jp2_create.rb#L58
Relevant test: https://github.com/sul-dlss/common-accessioning/blob/main/spec/robots/assembly/jp2_create_spec.rb#L590-L596 
Existing tests
> remove honeybadger notification

- lib/dor/assembly.rb
This duplicates the functionality of `config/boot.rb`.
CI
> Remove unnecessary require

- lib/robots/dor_repo/assembly/jp2_create.rb
- spec/robots/assembly/jp2_create_spec.rb
Fixes #935
Having derivatives on objects with dark access causes the object to fail cocina validation.
CI
> Don't make jp2 derivatives for dark objects

- lib/robots/dor_repo/assembly/checksum_compute.rb
- spec/robots/assembly/checksum_compute_spec.rb
Closes #941, a production problem.
PR #919 had a mistake where the error message checksums not agreeing had variable that had been removed.  This fixes that problem.
I wrote a spec for this.  (codeclimate is in lululand)
> checksum_compute: fix error message when checksums do not agree

- lib/dor/assembly/item.rb
- lib/dor/assembly/stub_content_metadata_parser.rb
- lib/dor/file_sets.rb
Rather than the copy in assembly-objectfile
CI
> Use the local copy of ContentMetadata

- lib/dor/assembly/content_metadata.rb
- lib/dor/assembly/content_metadata/file_set.rb
- spec/lib/dor/assembly/content_metadata_spec.rb
These styles are never created in the StubContentMetadataParser, the only consumer of this code.
CI
> [refactor] Remove unused styles for generating contentMetadata

- lib/dor/assembly/content_metadata/file.rb
- lib/dor/assembly/content_metadata/nokogiri_builder.rb
- spec/lib/dor/assembly/content_metadata_spec.rb
These are never used in the stubContentMetadata case, which is the only use case using these methods
CI
> [refactor] Remove code around provider digests

- .gitignore
- lib/dor/assembly/content_metadata/file.rb
- spec/lib/dor/assembly/content_metadata_spec.rb
We never use this option, so we can simplify the code
> [refactor] Get rid of unused 'relative_path' option

- lib/dor/assembly/content_metadata/file.rb
- lib/dor/assembly/item.rb
- lib/dor/assembly/stub_content_metadata_parser.rb
- lib/dor/file_sets.rb
Because it's also used by accessioning
CI
> [refactor] Move ATTRIBUTES_FOR_TYPE out of assembly

- Gemfile
- Gemfile.lock
Latest assembly-objectfile gem is needed to avoid errors with accessioning ISO files.  Analog to https://github.com/sul-dlss/pre-assembly/pull/1061/files which bumped this gem for pre-assembly.
Should fix errors like this: https://app.honeybadger.io/projects/52894/faults/86871920, in objects like this: https://argo.stanford.edu/view/druid:pk733ww1123 
Existing tests
> Update assembly-objectfile to 2.1.x

- lib/robots/dor_repo/assembly/exif_collect.rb
- spec/robots/assembly/exif_collect_spec.rb
Fixes sul-dlss/assembly-objectfile#102
This commit further restricts which images receive presentation information (height/width) gathered by exif to the types currently returned by the existing `#valid_image?` method in the public API. These include TIFF, PNG, JPEG, and JP2. This prevents recording (perhaps bogus or nil) presentation information for image types that are unsupported for presentation elsewhere in SDR (e.g., the sul-embed service).
CI and tested successfully in a deployed env by @andrewjbtw
> Include presentation metadata only for select image types

- lib/dor/assembly/content_metadata_from_stub/structural_builder.rb
- lib/dor/file_sets.rb
- spec/fixtures/workspace/ab/123/cd/4567/content_metadata.xml
- spec/lib/dor/assembly/content_metadata_from_stub/structural_builder_spec.rb
- spec/robots/accession/content_metadata_spec.rb
- spec/test_input/bb/111/bb/5555/stubContentMetadata.xml
This commit patches more code paths that set the publish and shelve attributes, ensuring that dark objects have *no* files set to publish or shelve EVEN IF the stub content metadata says so. This is a problem with some Goobi objects, and this patch allows those items to continue accessioning.
CI, and will test in a deployed env with @andrewjbtw
> Turn off publish and shelve when dark in missed spots

- config/settings.yml
- lib/robots/dor_repo/accession/update_doi.rb
- spec/robots/accession/update_doi_spec.rb
Fixes sul-dlss/happy-heron#2750
This commit adds a new check to the accessioning robot: if the object is in the SDR Graveyard APO, skip the step entirely. This has the effect of making sure not to publish DOIs of decommissioned (soft-deleted) objects.
CI, + successfully tested in stage
> Skip update-doi robot when object is in graveyard APO

- lib/preserved_file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/preserved_file_uris_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
refs https://github.com/sul-dlss/technical-metadata-service/issues/398
To call techmd service with the now required basepath param.
Unit
> Adds basepath to techmd call.

- config/deploy/prod.rb
in conjunction with a change to the prod sidekiq configs that halves the number of worker threads on each VM, this will allow us to effectively double the compute resources given to each worker thread while keeping the total number of worker threads the same.
see https://github.com/sul-dlss/common-accessioning/issues/1069
part of #1069
🙊 
> add 4 new worker VMs to the prod cap deploy config

- lib/robots/dor_repo/release/update_marc.rb
- spec/robots/release/update_marc_spec.rb
done as a job because it could take a while to complete, and because we're single threading the jobs to prevent concurrent updates to work around mysterious Folio issues
part of the workaround for https://github.com/sul-dlss/dor-services-app/issues/4454
see also https://stanfordlib.slack.com/archives/C09M7P91R/p1691769829144859?thread_ts=1691702965.586219&cid=C09M7P91R
_TODO_: add a helpful note about this in cap deploy configs?
> update-marc step expects to queue a job (in dor-services-app) that actually does the work of updating the marc in Folio

- lib/robots/dor_repo/accession/update_orcid_work.rb
- spec/robots/accession/update_orcid_work_spec.rb
Send all items through update-orcid-work step since we need to make sure removed ORCID authors' works get updated in ORCID. 
Unit and deploy/testing to stage, integration tests
> Items do not skip update-orcid-work

- lib/robots/dor_repo/assembly/checksum_compute.rb
- spec/robots/assembly/checksum_compute_spec.rb
closes #1091
With targeted file updates, a file may not exist in the workspace.
Unit
> Re-use existing checksums for targeted file update.

- lib/robots/dor_repo/assembly/checksum_compute.rb
refs #1074
Need for speed.
Unit
> Change compute checksums to digest in single pass.

- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/reset_workspace.rb
- spec/robots/dor_repo/accession/end_accession_spec.rb
- spec/robots/dor_repo/accession/reset_workspace_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/4634
To prevent the workflow from proceeding until reset is actually completed by DSA job.
Unit, stage
> Change reset to a noop so DSA can set 'completed' when doing the actual work

- lib/preserved_file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/preserved_file_uris_spec.rb
closes https://github.com/sul-dlss/technical-metadata-service/issues/485
To handle the case in which files are omitted from the workspace because they are not changing.
Previously, techmd service was being told to generate techmd for them, but they didn't exist.
Unit
> Skip techmd for files that are not in workspace.

- Gemfile
- Gemfile.lock
let's not pin gems without a reason
I ran integration tests for every type of object / set of robots;  all passed.
> unpin 3 gems: config, druid-tools and sul_orcid_client

- lib/robots/dor_repo/accession/content_metadata.rb
- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/accession/publish.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
from Sandi Metz:
"When you read the next line of code out loud, does it tell you exactly what was in the comment?"
if so, the comment is noise.
ci, as it's comments only
> Accession workflow:  remove noise comments

- lib/preserved_file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/preserved_file_uris_spec.rb
Partially addresses https://github.com/sul-dlss/technical-metadata-service/issues/510. Reverts code changes in https://github.com/sul-dlss/common-accessioning/pull/1120/files and sends filepath URIs for all preserved files, whether or not in workspace. 
Unit, ran with pre-assembly on QA and with integration test branch that checks techmd.
> Send all preserved file info to techmd

- Gemfile
- Gemfile.lock
I believe we are not using the `sul_orcid_client` gem in this code (we may have before but now it is in DSA).  I don't see it being used anywhere in the code and it doesn't appear to be configured here either.
Here is an example of where it is configured in DSA: https://github.com/sul-dlss/dor-services-app/blob/main/app/jobs/update_orcid_work_job.rb#L39-L47 and no equivalent references in common-accessioning: https://github.com/search?q=repo%3Asul-dlss%2Fcommon-accessioning%20SulOrcidClient&type=code
CI
> not using sul_orcid_client in this code?

- Gemfile.lock
- lib/robots/dor_repo/accession/start_accession.rb
- spec/robots/dor_repo/accession/start_accession_spec.rb
Partnered with https://github.com/sul-dlss/workflow-server-rails/pull/748
Connects to sul-dlss/workflow-server-rails#738
CI
> Add StartAccession robot whose job is to alert if object is open

- lib/robots/dor_repo/assembly/accessioning_initiate.rb
- spec/robots/dor_repo/assembly/accessioning_initiate_spec.rb
closes #1162
Versioning normalization.
Unit, integration
> Changes accessioning initiate robot to close version.

- lib/dor/assembly.rb
I think this file may have been added because we want the "assembly" namespace for classes like `Dor::Assembly::Item`.  It also used to have other config/requires before it was all removed and placed elsewhere. So now I believe declaring an empty module like this is not necessary, as this is inferred from the folder structure of the class definition itself.
CI
> do not think we need this empty file

- Gemfile
- Gemfile.lock
- config/settings.local.yml
- lib/dor/text_extraction/ocr.rb
- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/ocr/ocr_create.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- spec/robots/dor_repo/accession/end_accession_spec.rb
- spec/robots/dor_repo/ocr/ocr_create_spec.rb
Fixes #1163 and fixes #1164
The end-accession robot will start the ocrWF as needed.
~~- check for metadata in cocina to determine if we need to start the ocrWF~~ deferred to later ticket #1203
~~Currently blocked by sul-dlss/cocina-models#705 until will resolve the cocina models decisions~~
Notes: 
- the logic for starting OCR workflow is not yet complete, we need to deal with the checks for cocina metadata still.
- captionWF is ignored for now, will add later when we actually work on it
> start ocr logic for end-accession

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- filter files for OCR based on type and filetypes.
fixes #1201 
RSPEC. ocr_file function tested on the server in console with `druid:qv402bt5465` and a type document druid.
> update ocr to filter files

- lib/robots/dor_repo/caption/caption_create.rb
- lib/robots/dor_repo/caption/end_caption.rb
- lib/robots/dor_repo/caption/start_caption.rb
- lib/robots/dor_repo/ocr/end_ocr.rb
- lib/robots/dor_repo/ocr/split_ocr_xml.rb
- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/caption/caption_create_spec.rb
- spec/robots/dor_repo/ocr/end_ocr_spec.rb
- spec/robots/dor_repo/ocr/ocr_create_spec.rb
- spec/robots/dor_repo/ocr/split_ocr_xml_spec.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
Opening a version requires a description -- this adds it.
It also removes the unnecessary `true` from being returned in places, and adjusts the tests accordingly.
on qa
> Fix open version code

- lib/dor/text_extraction/abbyy/ticket.rb
- spec/fixtures/ocr/cc333dd4444_abbyy_ticket.xml
- spec/fixtures/ocr/new_druid_abbyy_ticket.xml
- spec/lib/dor/text_extraction/abbyy/ticket_spec.rb
Rather than requiring the user of the Abbyy class to know that file
paths should be in a druid subdirectory using Windows file separator the
caller can just pass in the filenames and the Abbyy class will handle
making sure they are referenced in the XML using the druid subdirectory.
Also update the paths used so that they include the "bare" druid,
or only the identifier only includes the identifier portion, so
instead of '/tmp/druid:bb22ccc3333' it will be '/tmp/bb22ccc3333'.
Even though they are currently out of scope the ticket writing will also
handle when there is file hierarchy in the path: 'x/y.png' instead of
'y.png'.
Unit tests.
> Handle referencing files in druid subdirectory

- Gemfile
- Gemfile.lock
- lib/dor/text_extraction/ocr.rb
- lib/robots/dor_repo/ocr/fetch_files.rb
- lib/robots/dor_repo/ocr/ocr_create.rb
- spec/robots/dor_repo/ocr/fetch_files_spec.rb
- spec/spec_helper.rb
Add a workflow step for wfOCR to fetch files in need of OCR from preservation using the Preservation::Client.
Closes #1187
Unit tests. It's not actually part of the workflow yet...
> Add fetch_files for OCR

- Gemfile
- Gemfile.lock
- config/settings.yml
- lib/dor/text_extraction/abbyy/file_watcher.rb
- lib/dor/text_extraction/abbyy/ticket.rb
- lib/dor/text_extraction/workflow_updater.rb
- lib/robots/dor_repo/ocr/fetch_files.rb
- spec/lib/dor/text_extraction/abbyy/file_watcher_spec.rb
- spec/lib/dor/text_extraction/workflow_updater_spec.rb
- spec/robots/dor_repo/ocr/fetch_files_spec.rb
- spec/spec_helper.rb
- spec/support/abbyy_helper.rb
- Create a workflow updater service for text extraction
- Create a FileWatcher that emits events based on ABBYY jobs
#1231 will create a background service to run the `FileWatcher` using systemd.
> Create ABBYY file watcher

- lib/dor/text_extraction/abbyy/file_watcher.rb
- lib/dor/text_extraction/workflow_updater.rb
- spec/lib/dor/text_extraction/abbyy/file_watcher_spec.rb
- spec/lib/dor/text_extraction/workflow_updater_spec.rb
We have a specific way to put a step in error via the dor-workflow-client and this sets the error message correctly.
Updated specs
> use dor-workflow-client method to set step to error

- .rubocop.yml
* update deprecated rule names to their current counterparts
* add rules that are new since last .rubocop.yml update
ran rubocop, no violations detected, no longer saw deprecation warnings
> pay off a little rubocop tech debt

- lib/robots/dor_repo/ocr/fetch_files.rb
- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
Fixes #1255 - prevent ocrWF from starting if OCR is not possible to run
New specs
> stop ocrWF from starting if there are no OCRable files

- lib/dor/text_extraction/abbyy/split_alto.rb
- lib/robots/dor_repo/ocr/split_ocr_xml.rb
- spec/fixtures/ocr/bb999cc1111_abbyy_alto.xml
- spec/lib/dor/text_extraction/abbyy/split_alto_spec.rb
- spec/robots/dor_repo/ocr/split_ocr_xml_spec.rb
For some reason abbyy alto sometimes have a different value under sourceImageInformation (sometimes fileName, sometimes fileIdentifier). This just looks for nodes underneath sourceImageInformation.
Also if there is a PDF we don't get an alto to split so this makes sure that it doesn't try if the alto file doesn't exist.
Rspec
> fix split alto

- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
Fixes #1259 - mark all ocrWF steps as skipped instead of raising an error if the workflow is started but there is nothing to ocr.  This allows the object to be versioned and fixed if needed instead of putting it in error.
~~HOLD for testing on QA~~
See https://argo-qa.stanford.edu/view/druid:bv915yp9350 for test object on argo-qa that was skipped (google book with no images)
Updated specs
QA
> skip all steps in the ocrWF if object cannot be OCRed

- lib/capistrano/tasks/abbyy_watcher_systemd.cap
You don't need sudo to read the logs/status, but you apparently
do to restart the process!
> Use sudo to restart ABBYY watcher

- config/settings.yml
- lib/dor/text_extraction/abbyy/ticket.rb
- lib/dor/text_extraction/ocr.rb
- lib/robots/dor_repo/ocr/fetch_files.rb
- lib/robots/dor_repo/ocr/ocr_create.rb
- lib/robots/dor_repo/ocr/ocr_workspace_cleanup.rb
- lib/robots/dor_repo/ocr/split_ocr_xml.rb
- spec/lib/dor/text_extraction/abbyy/ticket_spec.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- spec/robots/dor_repo/ocr/ocr_workspace_cleanup_spec.rb
Fixes #1212 - clears out empty abbyy input and output folders and XML ticket file
Goes with https://github.com/sul-dlss/workflow-server-rails/pull/771
~~TODO: should we expect the OUTPUT to be empty?  or will have it leftover files that are safe to cleanup?~~ It will clear out non-empty folders
~~NOTE: until we actually complete the implementation of the stage-files robot, this workflow step will just error out each time, as nothing will be emptying the output folder, so we may want to hold off merging it for now.~~
New specs
> add abbyy workspace cleanup robot

- Gemfile.lock
- spec/robots/dor_repo/release/release_members_spec.rb
Required for removing ReleaseTag from cocina-models
> Switch Cocina::Model::ReleaseTag to Dor::Services::Client::ReleaseTag

- bin/abbyy_catchup
This adds a script that can be run in the event that the watcher process
goes down for some time while OCR is being processed. It checks ABBYY's
result and exception directories and manually updates the workflow
status for any items recorded there, so that the system can be informed
of changes that happened while the watcher was down.
This was tested by putting success/failure result XML files in the
relevant directories locally and invoking the script.
It's intended to not halt when there is an error communicating with
DSA or the workflow service, because some items may already have had
their status updated, so the calls to update them again will fail.
> Create a script that can be used to recover from ABBYY watcher failures

- lib/dor/text_extraction/abbyy/split_alto.rb
~~To address #1278 (hopefully) and maybe #1279~~
Does not seem to address #1278 or #1279 but I think we still want it.
The `<Description>` nodes are currently only added to the first page level XML document.  This ensures they get added to all.  Compare the working and non-working objects in the original ticket to see this.
~~HOLD for testing on QA~~
Localhost and QA
> ALTO XML split robot: ensure all expected nodes are in each split file

- lib/dor/text_extraction/cocina_updater.rb
- spec/lib/dor/text_extraction/cocina_updater_spec.rb
- spec/robots/dor_repo/ocr/update_cocina_spec.rb
Fixes #1285 - presuming we want to be consistent with our current approach the way pre-assembly does it, we would not set role=transcription for txt OCR files
see https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/from_staging_location/file.rb#L28-L38 for how pre-assembly is set up
Discussion: https://stanfordlib.slack.com/archives/C06EVDJV45N/p1718220321336929
Localhost
> do not set role=transcription for txt ocr files

- lib/robots/dor_repo/accession/end_accession.rb
- spec/robots/dor_repo/accession/end_accession_spec.rb
When we create ocrWF, it will be in the next object version (since the first step of ocrWF is open the object version).  So start ocrWF with the next version up.  This ensures workflow service and SDR remain in sync. 
QA
> ensure workflow versions match object versions

- lib/dor/text_extraction/abbyy/file_watcher.rb
- spec/lib/dor/text_extraction/abbyy/file_watcher_spec.rb
- spec/support/abbyy_helper.rb
Reverts sul-dlss/common-accessioning#1307
Turns out stage-files depends on the XML ticket file being there.  We should clean it up later (in the cleanup step)
> Revert "remove result.xml files after processing"

- lib/tasks/cleanup.rake
A rake task to cleanup empty/older files/folders in the ABBYY mount.
Useful to cleanup items now that have accumulated during development/testing.  Possibly useful in the future if/when we have breakdowns in the cleanup robot and or things get stalled in development and we need some extra cleanup.
Will add to devops docs too if approved
Fixes #1310
Localhost and directly on QA (with actual deletion commented out temporarily)
> cleanup script

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
Fixes #1314 - deletes the exception XML files after ocr-cleanup runs (presumably we have fixed errors if we reached this step).  This allows the abbyy_catchup script to be re-runnable so it won't reprocess these xml files.
Note that it won't cleanup images in the folder -- we don't know exactly which files go with which druids without more work.  The general cleanup rake task in #1313 can get to these later.
New spec
> cleanup exception XML files

- .rubocop.yml
- lib/dor/text_extraction/ocr.rb
- lib/tasks/cleanup.rake
* slight clarity improvements (to a comment, a rake task description, and some terminal output)
* slightly safer ABBYY OCR cleanup code
* keep up with rubocop rules
* ran unit tests locally
* ran modified rake task locally in both modes, after running unit tests, so that there'd be test data to clean up
> Miscellaneous touchups (mostly to OCR cleanup)

- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
In order to correctly retry a situation where the object cannot be opened in start-ocr because it thinks it is still being accessioned, we need to rescue the correct exception.  
Here is an example showing what is raised when this happens: https://app.honeybadger.io/projects/52894/faults/108881704
```
Dor::Services::Client::UnexpectedResponse: Unable to open version (Object net yet accessioned)
exception_class = EXCEPTION_CLASS.fetch(response.status, UnexpectedResponse)
raise exception_class.new(response: response,
object_identifier: object_identifier,
errors: data.fetch('errors', []))
```
This changes the rescue clause to catch the correct error: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client.rb#L43-L55
coming from …
> rescue for the correct exception for a retry

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/release/release_publish.rb
- spec/robots/dor_repo/release/release_publish_spec.rb
Fixes #1325 - use only public release tags to ensure we don't incorrectly delete something that should actually be released.
Follow on from https://github.com/sul-dlss/dor-services-client/pull/455 which adds the ability to call this public param in DSA
New spec
> use new public: true tag for releases

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
Allow for more time to retry the ocr cleanup step, since we are seeing some file latency issues in stage.  See https://app.honeybadger.io/projects/52894/faults/109731242/01J3G1TY9JXXT59N9QJPETQF0N
This issue was sporadic while running integration tests.  Will also follow up with OPs
Localhost with updated CI
> allow more time for cleanup retries

- lib/dor/text_extraction/abbyy/results.rb
- lib/dor/text_extraction/ocr.rb
- lib/robots/dor_repo/ocr/stage_files.rb
- spec/lib/dor/text_extraction/abbyy/results_spec.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- spec/robots/dor_repo/ocr/stage_files_spec.rb
Does five things:
1. Do not send an HB alert each time we attempt to retry deletion of a folder.  This better mimics what is done elsewhere in the code here https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/ocr/fetch_files.rb#L47-L60 where we only alert if there is an eventual failure.
2. Do not parse the result XML file if we only need to see if a file exists with `find_latest`, otherwise the ocr-workspace-cleanup step is going to have to  unnecessary re-parse that XML file when it all wants to do is delete the file.
3. Stop this HB alert from triggering for PDF docs (which do not have an ALTO file to parse): https://app.honeybadger.io/projects/52894/faults/111166939
4. Adds an extra retry to the cleanup (was still seeing some flakiness even on main)
5. Adds …
> do not HB alert on each retry; reduce parsing of XML

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
Running test suite is slow locally when you have to wait for a lot of retries with a long wait time between each.  This lets us set it so we can wait less if needed (e.g. for testing).
Unit tests
> speed up testing by allowing backoff to be set for open version retries

- lib/dor/text_extraction/file_fetcher.rb
- lib/dor/text_extraction/ocr.rb
- lib/dor/text_extraction/version_updater.rb
- lib/robots/dor_repo/ocr/fetch_files.rb
- lib/robots/dor_repo/speech_to_text/fetch_files.rb
- spec/lib/dor/text_extraction/file_fetcher_spec.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- spec/lib/dor/text_extraction/version_updater_spec.rb
- spec/robots/dor_repo/ocr/fetch_files_spec.rb
- spec/robots/dor_repo/speech_to_text/fetch_files_spec.rb
Fixes #1345 
The ocr `fetch-files` robot contains functionality that we will need for the new speech-to-text `fetch-files` robot -- namely pulling content down from preservation and writing to disk (or sending to the cloud).
This PR:
1. Creates a new class do to this and moves the part of the code related to fetching files from preservation and writing them to disk over to the new class.
2. Adds stub methods in this new class that can be implemented later to send content to the cloud.
3. Updates the existing ocr `fetch-files` robot to use the new class.
4. Stubs out the new speech-to-text `fetch-files` robot to use the new class.
5. Move and update the tests from the robot to the new class, and simplify them a bit so it doesn't mock out all of the cocina and DSA stuff for getting …
> refactor fetch-files robot into own class

- lib/dor/text_extraction/ocr.rb
- lib/dor/text_extraction/speech_to_text.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
Fixes #1346 - adjust logic for which files to select for speech to text.  This sets it so that (1) only files that are both shelved and preserved are selected, (2) only files with mimetype of `audio/mp4` or `video/mp4` are selected, (3) only files in a resource type of `audio` or `video` are selected, (4) only object types of type `media` will be considered.  Any number of files that match in any given resource type will be selected.
Updated specs
> adjust selection criteria for speech to text files

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
We get issues sometimes with an empty folder claiming it cannot be deleted with FileUtils even when it is empty.  This seems to work better (delete happened right away with no retries in my integration test run)
Updated specs.  Deploy to stage and integration tests.
> shell out to try and delete folders instead of FileUtils

- lib/dor/text_extraction/speech_to_text.rb
- lib/robots/dor_repo/speech_to_text/fetch_files.rb
- lib/robots/dor_repo/speech_to_text/stt_create.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
- spec/robots/dor_repo/speech_to_text/fetch_files_spec.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
Fixes #1371 - job id is now druid-version and so is the place where we put the files in S3 bucket
Spec
> adjust job-id params and namespace for sending files to s3

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/accession/reset_workspace.rb
- lib/robots/dor_repo/dissemination/cleanup.rb
- spec/robots/dor_repo/accession/end_accession_spec.rb
- spec/robots/dor_repo/accession/reset_workspace_spec.rb
- spec/robots/dor_repo/dissemination/cleanup_spec.rb
Part of https://github.com/sul-dlss/dor-services-app/issues/5110
Fixes #1322
Remove the call to `cleanup` from end-accession robot.  We will instead do this from the existing reset-workspace robot.  Note that we don't need the call to the `reset` endpoint because all of it's work is already done by cleanup.  The `reset` endpoint is going away in the related DSA and dsa-client PRs.  
We need to coordinate changes in [DSA](https://github.com/sul-dlss/dor-services-app/pull/5183)
Deploy this first before DSA.
Specs
Integration tests
> Remove cleanup from end accession

- lib/robots/dor_repo/accession/reset_workspace.rb
- spec/robots/dor_repo/accession/reset_workspace_spec.rb
The reset-workspace step is calling an endpoint that will mark it as complete. There is no other workflow step that will ever call this job, so there is no need to pass in a workflow param anymore (it used to also be triggered by disseminationWF:cleanup, but that is gone, see #1385).
see https://github.com/search?q=org%3Asul-dlss+workspace.cleanup&type=code
This changes needs to be coordinated with https://github.com/sul-dlss/dor-services-app/pull/5186 and https://github.com/sul-dlss/dor-services-client/pull/475 which remove the param from the call.
HOLD for #1385
Process:
1. Merge https://github.com/sul-dlss/dor-services-client/pull/475 and then cut a new release
2. Update https://github.com/sul-dlss/common-accessioning/pull/1386 to use new dor-services-client release, merge it
3. Merge …
> remove workflow param from cleanup

- Gemfile
- Gemfile.lock
Removal of the workflow param from the cleanup call (https://github.com/sul-dlss/dor-services-client/pull/475) means we should use the new gem.
CI
> update dsa client

- spec/robots/dor_repo/speech_to_text/stage_files_spec.rb
follow-on from https://github.com/sul-dlss/common-accessioning/pull/1398
wasn't any more work to do this than leave a comment, and the PR otherwise looked great and passed integration tests
unit tests
> stage_files_spec.rb: make test of aws_provider.client.get_object more realistic

- lib/dor/text_extraction/file_fetcher.rb
Fixes #1392 by catching the 404 from preservation before we get to trying to pull from S3 and doing a retry (same as we do when trying to write to disk for OCR).
Integration tests (worked three times in a row with integration test)
> Address S3 flakiness on upload

- bin/speech_to_text_watcher
- config/settings.yml
- lib/dor/text_extraction/abbyy/file_watcher.rb
- lib/dor/text_extraction/aws_provider.rb
- lib/dor/text_extraction/dor_event_logger.rb
- lib/dor/text_extraction/speech_to_text_create_done_handler.rb
- lib/dor/text_extraction/sqs_watcher.rb
- lib/dor/text_extraction/workflow_updater.rb
- spec/lib/dor/text_extraction/abbyy/file_watcher_spec.rb
- spec/lib/dor/text_extraction/aws_provider_spec.rb
- spec/lib/dor/text_extraction/dor_event_logger_spec.rb
- spec/lib/dor/text_extraction/speech_to_text_create_done_handler_spec.rb
- spec/lib/dor/text_extraction/sqs_watcher_spec.rb
- spec/lib/dor/text_extraction/workflow_updater_spec.rb
part of #1358
- unit tests
- ran the daemon locally at debug log level
- configured to point to my own test queues
- commented out the calls to report to DOR event log and workflow service
- created and worked a test job using [the tools in speech-to-text for creating test jobs](https://github.com/sul-dlss/speech-to-text?tab=readme-ov-file#run)
- watched the job get picked up by this daemon, saw the message body get parsed properly based on log statements
- stopped the daemon and uncommented the calls to report to DOR event log and workflow service
- created another test job
- watched the daemon log an error because i don't have my local common-accessioning instance configured to talk to a real dor-services-app or workflow-server-rails instance
- watched the daemon sit there for the …
> Speech to text watcher

- lib/dor/text_extraction/speech_to_text.rb
As per discussion here: https://stanfordlib.slack.com/archives/C06EVDJV45N/p1731011602548429
Should still work as is because of the `Assembly::ObjectFile` gem computes the mimetype as `audio/mp4` for our test object.  This would allow the other mimetype through to be captioned as well.
Updated spec
> adjust mimetype for allowed audio files for speech to text

- lib/robots/dor_repo/speech_to_text/stage_files.rb
- spec/robots/dor_repo/speech_to_text/stage_files_spec.rb
Fixes #1408 - filter out unnecessary caption files when pulling them from S3
~~HOLD for integration test~~
Updated spec
Integration test
> only include .txt and .vtt files produced by whisper in object

- bin/speech_to_text_watcher
- lib/dor/text_extraction/sqs_watcher.rb
- spec/lib/dor/text_extraction/sqs_watcher_spec.rb
* fixes #1407
* other quality of life improvements (cleaner exit from watcher script, better logging)
- this worked, see retry HB alert from manual test, and retry exceeded alert from same: https://app.honeybadger.io/projects/52894/faults/114641176 and https://app.honeybadger.io/projects/52894/faults/114641232
what exit looked before this PR
```
^C** [Honeybadger] Unable to send error report: API key is missing.
jmartin-sul/.rbenv/versions/3.2.2/lib/ruby/3.2.0/net/protocol.rb:229:in `wait_readable': Interrupt
from …
```
> limit retries when SQS watcher picks up job

- lib/dor/text_extraction/ocr.rb
- lib/dor/text_extraction/speech_to_text.rb
- spec/lib/dor/assembly/content_metadata_from_stub/structural_builder_spec.rb
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
- spec/robots/dor_repo/assembly/checksum_compute_spec.rb
- spec/robots/dor_repo/assembly/exif_collect_spec.rb
- spec/robots/dor_repo/assembly/jp2_create_spec.rb
- spec/robots/dor_repo/ocr/fetch_files_spec.rb
- spec/robots/dor_repo/ocr/update_cocina_spec.rb
- spec/robots/dor_repo/ocr/xml_ticket_create_spec.rb
- spec/robots/dor_repo/speech_to_text/fetch_files_spec.rb
- spec/robots/dor_repo/speech_to_text/stage_files_spec.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
- spec/robots/dor_repo/speech_to_text/update_cocina_spec.rb
- spec/spec_helper.rb
Fixes #1403 and fixes #1404
Do not send files that will not be OCRed or captioned off to the service (i.e. ignore things that are marked as correctedForAccessibility OR were not sdr generated)
Question: should we look at the role instead of the extension? 
Also: refactor the tests and code to use cocina model constants instead of strings, e.g. `Cocina::Models::FileSetType.image` instead of `https://cocina.sul.stanford.edu/models/resources/image` and similar for object types
I tried to make the logic match what is used at the end in cocina-updater, which is ignoring a file if there is a corresponding caption/ocr file that is (1) marked as "correctedForAccessibility" OR (2) NOT "sdrGenerated".  The logic is we are only overwriting caption/ocr files in the case they were both sdrGenerated …
> skip files marked as corrected for accessibility

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
This PR https://github.com/sul-dlss/common-accessioning/pull/1415/files inadventantly added an extra condition for files to be OCRable, which is that they are shelved as well as preserved.  Previously the condition had been that only preserved was required (since we pull them down from preservation for OCRing).  This makes the condition what it was previously.
Related question for a different PR: should I also do this for speech to text?
Spec
> shelving is not required for ocring

- lib/dor/text_extraction/speech_to_text.rb
- lib/robots/dor_repo/speech_to_text/stt_create.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
- spec/spec_helper.rb
Fixes #1427 - adds the `languageTag` from cocina to the SQS message for the object so it can be passed through to Whisper.  The languageTag can be set in pre-assembly via the file manifest.
Note that this change must be coordinated with work done for https://github.com/sul-dlss/speech-to-text/issues/51 .  Since the format of the message has changed, the whisper container needs to know how to process and deal with this new format.
Specs
> add language tag from cocina to sqs message

- lib/dor/text_extraction/cocina_updater.rb
- lib/dor/text_extraction/speech_to_text_cocina_updater.rb
- spec/lib/dor/text_extraction/speech_to_text_cocina_updater_spec.rb
- spec/robots/dor_repo/speech_to_text/update_cocina_spec.rb
Preserve json files coming from whisper
Example integration test object: https://argo-qa.stanford.edu/view/druid:ys412hp1997
Updated integration test to go with this: https://github.com/sul-dlss/infrastructure-integration-test/pull/801
closes #1430 
Updated specs
integration test
> preserve json output file from whisper

- bin/console
So we can start the bin/console script the same way we start a rails console to set the environment (while still supporting the old ways)
Localhost
> allow bin/console script environment to be set like rails console

- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/qa.rb
- config/deploy/stage.rb
- lib/capistrano/tasks/speech_to_text_watcher_systemd.cap
closes #1413 
hold for (depends on)
i was able to successfully run the `status` task against stage and qa, e.g.:
```
% be cap stage speech_to_text_watcher_systemd:status
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
00:00 speech_to_text_watcher_systemd:status
01 systemctl status speech_to_text_watcher
01 ● speech_to_text_watcher.service - speech_to_text_watcher
01      Loaded: loaded (/etc/systemd/system/speech_to_text_watcher.service; enabled; vendor preset: enabled)
01      Active: active (running) since Sun 2024-11-24 09:53:19 PST; 1 weeks 5 days ago
01    Main PID: 903 (ruby)
01       Tasks: 3 (limit: 9457)
01      Memory: 92.0M
01      CGroup: /system.slice/speech_to_text_watcher.service …
```
> manage speech_to_text_watcher using capistrano and systemd

- spec/lib/dor/text_extraction/file_fetcher_spec.rb
Fixes #1379 - use HTTP mocking of calls in spec instead of double of client
Spec
> mock pres-client calls instead of double of client

- Gemfile
- Gemfile.lock
- config/settings.yml
- lib/dor/text_extraction/aws_provider.rb
- lib/robots/dor_repo/speech_to_text/stt_create.rb
- spec/lib/dor/text_extraction/aws_provider_spec.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
To allow for automatic provisioning of GPU ready EC2 instances we are going to use AWS Batch instead of running a dedicated EC2 instance. This means that work needs to be submitted to a Batch Queue instead of SQS. Since Batch doesn't have any facility for sending notifications on job completion we are still going to keep the "done" SQS queue.
These changes are dependent on Terraform configuration work for AWS Batch in https://github.com/sul-dlss/terraform-aws/pull/1197
Resolves #1453
CI and Integration Tests in QA
> Submit speech-to-text job to AWS Batch

- lib/dor/assembly/stub_content_metadata_parser.rb
- lib/robots/dor_repo/assembly/content_metadata_create.rb
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
- spec/robots/dor_repo/assembly/content_metadata_create_spec.rb
- spec/test_input/bb/111/bb/7777/stubContentMetadata.xml
Fixes #1477 
Currently partial and malformed stubContentMetadata.xml that is exported from Goobi is happily processed but results in incomplete objects.  This change will now cause an error to be raised and thus put the content-metadata-create step to be placed in error with an appropriate message if this happens.
See https://stanfordlib.slack.com/archives/C0EAZ09QF/p1743445147202589 for the reasoning behind this change.
Note: it also reverts #1475 since we don't need that anymore (this will put the step in error, leaving the file in the workspace for further debugging)
New specs
> raise an error on invalid stubContentMetadata

- lib/robots/dor_repo/assembly/content_metadata_create.rb
- spec/robots/dor_repo/assembly/content_metadata_create_spec.rb
Follow on for #1477 
We discovered that the stubContentMetadata.xml file seems to be complete if you wait for a bit.
This could be because:
(1) goobi is writing the files at the same time as the make the API call (synchronously) and we have a race condition
(2) our shared mounts are out of date (i.e. goobi writes to a shared file system, but when we try and read the same file from a different VM what mounts that shared file system, it takes some time for the file to appear complete).
If (1) is true, then goobi should fix this on their end and we shouldn't need this code (but it will help in the meantime).
If (2) is true, then this may be the most expedient solution and mimics what we do in other places (like speech to text and OCR work) to get around the shared file system latency issue. …
> add retries around stub content metadata generation

- .rubocop.yml
- Gemfile.lock
- lib/robots/dor_repo/accession/start_accession.rb
- spec/fixtures/staging/dd/116/zh/0343/dd116zh0343/content/folder1PuSu/story4u.txt
- spec/robots/dor_repo/accession/start_accession_spec.rb
closes #1513
To address a latency between files being written to staging and files being visible on all staging mounts.
Unit, qa
> Check files are present before starting accessioning.

- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/ocr/xml_ticket_create.rb
- spec/fixtures/ocr/bb222cc3333_abbyy_ticket_multilingual.xml
- spec/fixtures/ocr/bb222cc3333_abbyy_ticket_spanish.xml
- spec/lib/dor/text_extraction/abbyy/ticket_spec.rb
- spec/robots/dor_repo/accession/end_accession_spec.rb
- spec/robots/dor_repo/ocr/xml_ticket_create_spec.rb
Fixes https://github.com/sul-dlss/common-accessioning/issues/1495 
1. We need to ensure that when the new version is created with the captioning workflow (be it ocrWF or speechToTextWF), so we are preserving the workflow context from the previous version.  This is because pre-assembly will have set this version context (i.e. the  language selection) in v1, and we need this in the next version so that the ocr/speechToText workflows can use it when running.
2. Add some new specs to verify the abbyy ticket that is created has the languages passed in from the workflow context
3. Fix rubocop deprecation warnings and add new cops
~~HOLD:~~
~~- test again~~
~~- remove TODO debug lines~~
~~- rebase https://github.com/sul-dlss/common-accessioning/pull/1516 and then adjust new fixture files here~~ …
> Pass in workflow context when creating new version

- lib/robots/dor_repo/accession/start_accession.rb
- spec/robots/dor_repo/accession/start_accession_spec.rb
Auditing was failing for dark files.
Unit
> Handles dark files when auditing in start-accession.

- lib/robots/dor_repo/release/release_members.rb
- spec/robots/dor_repo/release/release_members_spec.rb
releaseWF was being created for the collection, not the members. This was causing widespread mayhem.
Unit
> Create releaseWF for members not the collection.

- lib/dor/text_extraction/cocina_updater.rb
- spec/lib/dor/text_extraction/cocina_updater_spec.rb
- spec/lib/dor/text_extraction/ocr_cocina_updater_spec.rb
- spec/lib/dor/text_extraction/speech_to_text_cocina_updater_spec.rb
Fixes #1536 - access rights for new files generated by OCR/speech-to-text should match the default object rights, and not "world/world"
New specs
Todo:
> use object access rights when adding ocr/speech to text files
