sul-dlss/common-accessioning

- config/deploy/staging.rb
This PR removes the 3 and 4 robots VMs in stage. They are gone. @eefahy
> remove 3 and 4 which are gone now -- see SAR-2863

- robots/accession/embargo_release.rb
> Updating Solr field names to match new index.

- robots/accession/embargo_release.rb
> Fix Solr query quotes in order to actually return results.

- Gemfile
- Gemfile.lock
- robots/accession/embargo_release.rb
- spec/robots/accession/embargo_release_spec.rb
(sadly, this did NOT allow us to get the failures with release_embargo we are experiencing in situ, but it still seems like a grand idea to have specs.)
@peetucket @atz   might you review this?  Thanks. @cbeer @drh-stanford ?  Anyone?  it's pretty simple.
connects to #63
> embargo_release: make it a class and write tests

- config/deploy/dev.rb
i can successfully deploy to dev with this branch.
@peetucket @drh-stanford
closes #67
> config/deploy/dev.rb: remove non-existent hosts

- Gemfile
- Gemfile.lock
@jmartin-sul this PR upgrades dor-services
> upgrade to dor-services 5.10.0

- .travis.yml
> Test on ruby 2.4.1

- .travis.yml
prep work for ruby upgrade in sul-robots-test
> Add build for ruby 2.3.7

- spec/spec_helper.rb
> Move coverage to the top of spec_helper

- Rakefile
> Handles cases when rubocop is not present.

- robots/accession/sdr_ingest_transfer.rb
The instance method is deprecated
> Use the SdrIngestService to transfer.

- robots/accession/end_accession.rb
- spec/robots/accession/end_accession_spec.rb
> Don't kick off a workflow if it's blank

- Gemfile.lock
> Update dor-services to fix NoMethodError

- robots/accession/abstract_metadata.rb
- robots/accession/content_metadata.rb
- spec/robots/accession/content_metadata_spec.rb
Item#build_datastream is deprecated
> Switch to Dor::DatastreamBuilder

- bin/repub
- robots/accession/publish.rb
- spec/robots/accession/publish_spec.rb
Avoid deprecated obj.publish_metadata
> Use the new PublishMetadataService

- Gemfile.lock
this supports the rails-workflow-service
> Update dor-workflow-service to 2.4.0

- config/robots.yml
so `rake robots:verify` works as expected
> add release robots to robots.yml file 

- lib/publish_metadata_service.rb
- robots/accession/publish.rb
- robots/release/release_publish.rb
- spec/robots/release/release_publish_spec.rb
the publish_metadata instance method is deprecated
> Update ReleasePublish to use PublishMetadataService

- lib/dor/release/item.rb
- robots/goobi/goobi_notify.rb
- robots/release/release_members.rb
- robots/release/release_publish.rb
- robots/release/update_marc.rb
- spec/lib/dor/item_spec.rb
This provides consistency with how the other robots suites work
> Hardcode workflow names

- lib/datastream_builder.rb
All datastreams on this code path have a saved object
> Remove an unnecessary conditional

- config/schedule.rb
verify.log was part of robot-controller
> Remove verify.log now that we are using resque-pool

- bin/run_marc_builder.sh
This is referenced in the config/schedule.rb
> Copy the missing run_marc_builder.sh from etd_robots

- lib/dor/release/item.rb
- robots/dor_repo/etd_submit/start_accession.rb
And use the correct username and password everywhere
Fixes #274
> Only initialize the Dor::Services::Client one time

- lib/models/etd.rb
- robots/dor_repo/etd_submit/catalog_status.rb
- robots/dor_repo/etd_submit/check_marc.rb
- robots/dor_repo/etd_submit/other_metadata.rb
- robots/dor_repo/etd_submit/submit_marc.rb
> Avoid unnecessary require

- lib/dor/assembly.rb
- robots/dor_repo/assembly/base.rb
- robots/dor_repo/assembly/jp2_create.rb
- spec/robots/assembly/accessioning_initiate_spec.rb
- spec/robots/assembly/checksum_compute_spec.rb
- spec/robots/assembly/exif_collect_spec.rb
- spec/robots/assembly/jp2_create_spec.rb
> Removes hardcoded configuration.

- lib/models/etd.rb
- robots/dor_repo/etd_submit/other_metadata.rb
- spec/models/etd_spec.rb
Fixes https://github.com/sul-dlss/hydra_etd/issues/211
> etd robots expect etd models

- Gemfile
- Gemfile.lock
- spec/robots/etd_submit/other_metadata_spec.rb
> Systemu is required for etd-submit:other-metadata

- Gemfile
- Gemfile.lock
This will test to see if the connection errors are caused by redis 4.1.1
> Downgrade redis to 4.1.0

- config/environments/test.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/accession/embargo_release_spec.rb
- spec/robots/goobi_notify_spec.rb
It should just be using Settings.dor_services.url
> Don't set Dor::Config.dor_services.url

- Rakefile
Per https://github.com/nevans/resque-pool#rake-task-config
I'm hoping this might address timeout issues.
> Add resque-pool after_prefork hook

- config/boot.rb
> fix for zeitwerk loading issue when running embargo metadata script

- Gemfile.lock
> Bump assembly-image version to pick up a fix related to uncompressed TIFFs

- Gemfile
- Gemfile.lock
- config/boot.rb
- spec/robots/goobi_notify_spec.rb
And remove now unsupported configuration options: `username` and `password`
> Bump to dor-services-client 2.0.0 and dor-services 7.2.4

- lib/robots/dor_repo/accession/reset_workspace.rb
> Switched where reset_workspace robot get local_export_home.

- Gemfile.lock
This fixed a bug in getting workflows
n/a
> Upgrade dor-workflow-client

- lib/robots/dor_repo/assembly/accessioning_initiate.rb
Documentation was missing.
n/a
> Add documentation about what happens in accessioning-initiate

- lib/robots/dor_repo/accession/reset_workspace.rb
> Add documentation about reset workspace.

- config/settings.yml
- lib/robots/dor_repo/accession/sdr_ingest_transfer.rb
- lib/sdr_ingest_service.rb
- spec/lib/sdr_ingest_service_spec.rb
- spec/robots/accession/sdr_ingest_transfer_spec.rb
Reverts sul-dlss/common-accessioning#455
Let's discuss this tomorrow.
> Revert "Call the SdrIngestService in dor-services-app"

- lib/sdr_ingest_service.rb
- spec/lib/sdr_ingest_service_spec.rb
To stop getting deprecation messages in Honeybadger from dor-services-app about #ds_manifest.
n/a
> SdrIngestService uses pres-client to get SignatureCatalog

- lib/dor/release/item.rb
- spec/lib/dor/release/item_spec.rb
- spec/robots/release/release_members_spec.rb
- spec/spec_helper.rb
This code isn't actually used.
n/a
> Remove unused code

- config/resque-pool.yml
To support low priority queues for all workflows.
No.
> Adds -low queues. closes #317

- lib/dor/assembly/stub_content_metadata_parser.rb
There was no documentation about this.
yes
> Add documentation about stubContentMetadata.xml

- lib/robots/dor_repo/accession/provenance_metadata.rb
- spec/robots/accession/provenance_metadata_spec.rb
So that common-accessioning will no longer depend on Fedora
Fixes #528 
n/a
> Update provenance without hitting Fedora

- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/robots/accession/technical_metadata_spec.rb
This will assist in helping us break the dependency on Fedora
n/a
> Encapsulate the Fedora object just to where it's needed

- lib/robots/dor_repo/accession/technical_metadata.rb
- lib/technical_metadata_service.rb
- spec/lib/technical_metadata_service_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
This eliminates the dependency on ActiveFedora and PreservationCatalog on this class
n/a
> Do dependency injection on TechnicalMetadataService

- lib/robots/dor_repo/accession/shelve.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/robots/accession/shelve_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
> Don't run techMetadata or shelve when there are no files

- lib/robots/dor_repo/accession/descriptive_metadata.rb
I'm not sure we need to support this pathway.
n/a
> Add experiment around descMetadata

- lib/robots/dor_repo/accession/technical_metadata.rb
This begins a refactor where we move two methods to dor-service-app calls.
This future refactor will remove the dependency on preservation_catalog
and reduce the fedora dependency.
> Refactor the technical_metadata robot

- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
>  Test for stub_content_metadata

- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/dissemination/cleanup.rb
- spec/robots/accession/end_accession_spec.rb
refs #428
The DisseminationWF doesn't do anything.
No.
> Merge Accessioning end-accession and Dissemination workflow.

- config/deploy.rb
- config/environments/production.rb
- config/environments/test.rb
- config/settings.yml
- config/settings/test.yml
This is now completely set by settings.yml, so we don't need this file to stay in shared_configs
n/a
> Check in the environment config.

- lib/robots/dor_repo/release/release_members.rb
- spec/robots/release/release_members_spec.rb
This fixes an error:
```
ArgumentError:
wrong number of arguments (given 1, expected 0)
```
Fixes #565
n/a
> Use max_by rather than max

- lib/robots/dor_repo/etd_submit/check_marc.rb
- spec/robots/etd_submit/check_marc_spec.rb
This helps decouple common-accessioning from Fedora 3
Depends on https://github.com/sul-dlss/dor-services-app/pull/684
Ref #582 
n/a
> Use the dor-services-app to create identityMetadata for ETDs

- config/environments/production.rb
- config/environments/test.rb
- lib/robots/dor_repo/etd_submit/build_symphony_marc.rb
- lib/robots/dor_repo/etd_submit/catalog_status.rb
- lib/robots/dor_repo/etd_submit/check_marc.rb
- lib/robots/dor_repo/etd_submit/other_metadata.rb
> Removal global constants

- lib/file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/file_uris_spec.rb
Fixes https://github.com/sul-dlss/technical-metadata-service/issues/116
no
no
> Add support for files with spaces

- Gemfile
- Gemfile.lock
- config/boot.rb
- config/settings.yml
These are not used anymore
no
no
> Remove unused gems

- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/stage.rb
Apparently the setting in deploy.rb does not take effect in specific envs.
:disappointed: 
Sorry.
> Fix honeybadger, take three

- Gemfile.lock
Update to latest dor-services-client.
No.
No.
> Updates dor-services-client to 6.3.1.

- lib/dor/assembly/content_metadata.rb
- lib/robots/dor_repo/assembly/content_metadata_create.rb
- spec/robots/assembly/content_metadata_create_spec.rb
This code was never used.  Andrew approved this functionality change.
Test suite.
n/a
> Stop creating basic contentMetadata.xml

- Gemfile.lock
> Bump cocina-models

- config/deploy/prod.rb
See https://github.com/sul-dlss/operations-tasks/issues/2352
N/A
DevOpsDocs PR is forthcoming
> Decommission commmon-accessioning-prod-e

- Gemfile.lock
d'oh - because i forgot to generate the Gemfile.lock for PR #718
> update for new cocina-models

- Gemfile.lock
> Update cocina-models to 0.48.0

- Gemfile
- Gemfile.lock
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
Fixes #746 - update build for latest changes in assembly-objectfile
Tests
> fix build for latest assembly-objectfile

- Gemfile.lock
Connects to sul-dlss/argo#2404
Fixes sul-dlss/argo#2620
CI and will be tested in QA
None
> Bump DSC and cocina models

- Gemfile
- Gemfile.lock
- spec/robots/assembly/jp2_create_spec.rb
Keep up to date on dependencies.
> Update activesupport to 6.1

- Gemfile.lock
Part of sul-dlss/dor-services-app#2851
> bump cocina-models for new lane barcode validation

- Gemfile
- Gemfile.lock
> Update to cocina-models 0.61.0

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/update_doi.rb
- spec/robots/accession/update_doi_spec.rb
> Add a robot to update the DOI metadata

- README.md
Easily find the workflow definitions.
> Add information to readme about workflow definitions

- config/resque-pool.yml
Preparing to migrate techmd-prod to Ubuntu
N/A
N/A
> Shut down workers for techmd migration

- config/resque-pool.yml
Reverts sul-dlss/common-accessioning#806
> Revert "Shut down workers for techmd migration"

- Gemfile
- Gemfile.lock
Keep up to date with dependencies.
> Update dependency on activesupport to 7

- config/resque-pool.yml
Reverts sul-dlss/common-accessioning#809
> Revert "Shut down common-accessioning workers"

- .circleci/config.yml
> Switched to sul-dlss/ruby-rails for circle coonfig.

- lib/dor/file_sets.rb
- lib/dor/structural_metadata.rb
- lib/dor/viewing_direction_helper.rb
- lib/robots/dor_repo/accession/content_metadata.rb
- spec/lib/dor/structural_metadata_spec.rb
- spec/robots/accession/content_metadata_spec.rb
Hold until @andrewjbtw has tested this.
Fixes #827
> [HOLD] Transform contentMetadata to cocina on load

- lib/robots/dor_repo/accession/descriptive_metadata.rb
- spec/robots/accession/descriptive_metadata_spec.rb
> Use the new mods update DSA endpoint for saving MODS

- config/resque-pool.yml
> Reduce the number of workers.

- lib/robots/dor_repo/accession/content_metadata.rb
So we can see what needs this robot.
> Add documentation to Accession::ContentMetadata robot

- lib/robots/dor_repo/assembly/jp2_create.rb
Follow on from #933 adding more context via a code comment
> add comment explaining why we do not overwrite existing jp2s

- lib/dor/assembly/content_metadata.rb
- lib/dor/assembly/content_metadata/config.rb
- lib/dor/assembly/content_metadata/nokogiri_builder.rb
- spec/fixtures/content_metadata/test.svg
- spec/lib/dor/assembly/content_metadata_spec.rb
There is no need to support the complexity of offering this as an option, since it's only ever set one way.
CI
> [refactor] Remove unused add_exif option

- lib/dor/assembly/content_metadata.rb
We never use this, so there is no need to have the code.
> [refactor] Remove unused option include_root_xml

- lib/dor/assembly/content_metadata/file.rb
> Remove unused delegates

- Gemfile
- Gemfile.lock
We haz upgraded assembly-objectfile (gives better error messages for exif errors)
> update assembly-objectfile to version 2.1

- lib/dor/assembly/content_metadata_from_stub.rb
- lib/dor/assembly/content_metadata_from_stub/file_set.rb
- lib/dor/assembly/content_metadata_from_stub/nokogiri_builder.rb
- lib/dor/assembly/stub_content_metadata_parser.rb
- spec/lib/dor/assembly/content_metadata_from_stub_spec.rb
- spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb
The style obfuscates what is happening and has no relevance in this repo
CI
> [refactor] Replace style with object type

- Gemfile.lock
This should fix https://app.honeybadger.io/projects/52894/faults/86541414
> Update assembly-objectfile to the latest

- lib/robots/dor_repo/assembly/content_metadata_create.rb
Notify HB so we can see if this code path is being encountered anymore.
> notify honeybadger for what should be a dead-end code path now

- lib/preserved_file_uris.rb
- lib/robots/dor_repo/accession/technical_metadata.rb
- spec/lib/preserved_file_uris_spec.rb
- spec/robots/accession/technical_metadata_spec.rb
refs https://github.com/sul-dlss/technical-metadata-service/issues/383
Support metadata only updates.
> Support generating techmd for metadata only updates.

- Gemfile.lock
To deal with #1005 - time outs
> update dor-services-client to increase timeout

- lib/file_uri.rb
- spec/lib/file_uri_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/4256
> Handles spaces in filepaths.

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/dissemination/cleanup.rb
- spec/robots/accession/end_accession_spec.rb
- spec/robots/dissemination/cleanup_spec.rb
> End accession

- README.md
- Rakefile
- config/deploy.rb
Remove some lingering Resque things after the switch to Sidekiq.
> Remove Resque things

- .rubocop.yml
- lib/dor/assembly/content_metadata_from_stub/file_set.rb
- spec/lib/preserved_file_uris_spec.rb
- spec/robots/release/release_members_spec.rb
> add new rubocops and rubocop tweaks

- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/accession/update_orcid_work.rb
- spec/robots/accession/update_orcid_work_spec.rb
closes #1073
So that updating orcid work can be added to workflow.
Unit
> Adds update orcid work robot.

- .rubocop.yml
- lib/file_uri.rb
- spec/robots/assembly/exif_collect_spec.rb
Enables new cops and fixes linting updates
> Enable new cops and update specs

- README.md
tripped over it while making sure there were no changes needed for Folio cutover.
comment only.
> README made sparkling clear

- lib/robots/dor_repo/accession/update_doi.rb
Comments were wrong - fixed 'em
> fix comment copypasta

- Gemfile
- Gemfile.lock
> Update dependencies for cocina-models update

- Gemfile
- Gemfile.lock
> Bump DSC and lyber-core

- config/settings.yml
- lib/robots/dor_repo/assembly/content_metadata_create.rb
- spec/robots/dor_repo/assembly/content_metadata_create_spec.rb
> Remove handling of contentMetadata.xml from ContentMetadataCreate robot

- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/release/release_members.rb
- spec/robots/dor_repo/release/release_members_spec.rb
> Use the release tags api

- lib/robots/dor_repo/accession/technical_metadata.rb
Make it easier to understand what's happening here.
> Add comments about how technical metadata works

- lib/robots/dor_repo/assembly/start_assembly.rb
- spec/robots/dor_repo/assembly/start_assembly_spec.rb
Connects to sul-dlss/workflow-server-rails#750
CI
> Add robot to start assembly workflow

- .gitignore
- README.md
- lib/robots/dor_repo/caption/caption_create.rb
- lib/robots/dor_repo/caption/end_caption.rb
- lib/robots/dor_repo/caption/start_caption.rb
- lib/robots/dor_repo/ocr/end_ocr.rb
- lib/robots/dor_repo/ocr/ocr_create.rb
- lib/robots/dor_repo/ocr/split_ocr_xml.rb
- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/caption/caption_create_spec.rb
- spec/robots/dor_repo/caption/end_caption_spec.rb
- spec/robots/dor_repo/caption/start_caption_spec.rb
- spec/robots/dor_repo/ocr/end_ocr_spec.rb
- spec/robots/dor_repo/ocr/ocr_create_spec.rb
- spec/robots/dor_repo/ocr/split_ocr_xml_spec.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
Fixes #1168 and fixes #1169 and fixes #1179 - create starter robots for new captionWF and ocrWF
~~Waiting on sul-dlss/workflow-server-rails#757~~
Functionality to come later.
New stub specs
> add new robots for captioning and ocr

- README.md
> re-org read for common accessioning

- README.md
More useful for for developers in README
> add additional developer info to the readme

- lib/robots/dor_repo/assembly/content_metadata_create.rb
> Update documentation about content_metadata_create

- config/settings.yml
- lib/dor/text_extraction/abbyy.rb
- spec/fixtures/ocr/druid:bb222cc3333_abbyy_ticket.xml
- spec/fixtures/ocr/druid:new_druid_abbyy_ticket.xml
- spec/lib/dor/text_extraction/abbyy_spec.rb
- spec/robots/dor_repo/ocr/ocr_create_spec.rb
closes #1189 
- Via created tests in rspec
> functions to build abby ticket for processing

- config/settings.local.yml
To atone for my commit which broke the interwebs.
> remove settings.local.yml

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
> add more tests for TextExtraction::Ocr

- lib/robots/dor_repo/ocr/fetch_files.rb
To keep it consistent with the ruby class.
unit tests
> Rename workflow step

- lib/robots/dor_repo/ocr/fetch_files.rb
noticed this when doing a little poking around and testing for https://github.com/sul-dlss/common-accessioning/issues/1220
(existing) unit tests
> fix typo in reference to pres cat URL setting

- lib/robots/dor_repo/assembly/start_assembly.rb
- spec/robots/dor_repo/assembly/start_assembly_spec.rb
> Raise an error if assembly started when version is open

- lib/robots/dor_repo/accession/start_accession.rb
- spec/robots/dor_repo/accession/start_accession_spec.rb
> Raise an error if accession started when version is open

- spec/robots/dor_repo/accession/start_accession_spec.rb
- spec/robots/dor_repo/assembly/start_assembly_spec.rb
> Remove unnecessary stub of Honeybadger

- lib/robots/dor_repo/ocr/stage_files.rb
- lib/robots/dor_repo/ocr/update_cocina.rb
- lib/robots/dor_repo/ocr/xml_ticket_create.rb
- spec/robots/dor_repo/ocr/stage_files_spec.rb
- spec/robots/dor_repo/ocr/update_cocina_spec.rb
- spec/robots/dor_repo/ocr/xml_ticket_create_spec.rb
Add new ocrWF robots that will be filled in during the workcycle.  See https://github.com/sul-dlss/common-accessioning/issues/1166
Spec
> add new ocr robot placeholders

- lib/robots/dor_repo/ocr/xml_ticket_create.rb
- spec/robots/dor_repo/ocr/xml_ticket_create_spec.rb
- spec/support/abbyy_helper.rb
Fixes #1221 - implement xml-ticket-create robot
New spec
> write XML ABBYY ticket in robot step

- lib/robots/dor_repo/ocr/stage_files.rb
- lib/robots/dor_repo/ocr/update_cocina.rb
Fix typos in new OCR robots
Spec
> fix copypasta errors in new robots

- lib/robots/dor_repo/ocr/fetch_files.rb
- spec/robots/dor_repo/ocr/fetch_files_spec.rb
When Preservation doesn't know about a file keep trying 16 times with
an exponential backoff in between requests. This will sleep a maximum of 36
hours, afterwhich it will give up with an error. This is needed because
some objects may still be moving through preservationWF when ocrWF is
invoked.
Closes #1237
Unit tests / CI
> Retry when file not found in Preservation

- lib/dor/text_extraction/abbyy/results.rb
- spec/lib/dor/text_extraction/abbyy/results_spec.rb
Fixes #1266
Unit tests & testing in QA
> Copy all XML files except for Multi-page Abbyy XML

- config/deploy.rb
- lib/capistrano/tasks/abbyy_watcher_systemd.cap
The service definition is now managed in puppet.
> Remove the systemd service for the ABBYY watcher

- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
> allow ocrWF to run on already open versions

- config/settings.yml
- lib/dor/text_extraction/ocr.rb
Follow on from comments in #1249 
CI
> adjust settings for tests and adjust method signature

- lib/dor/text_extraction/abbyy/split_alto.rb
- lib/dor/text_extraction/ocr.rb
Trying to make XML page splits similar to what works
> Split page level xml changes

- Gemfile.lock
- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
Fixes #1299 
See https://github.com/sul-dlss/workflow-server-rails/issues/782
Tests won't pass until dor-workflow-client is updated.
QA+Rspect
> replace skip_workflow with endpoint

- lib/dor/text_extraction/abbyy/results.rb
We don't need this anymore because of #1271 
~~HOLD for testing on QA~~  Integration tests passed on QA
QA
> permissions are now set correctly on mount

- lib/robots/dor_repo/ocr/start_ocr.rb
- spec/robots/dor_repo/ocr/start_ocr_spec.rb
As a way to investigate/mitigate #1289 ?
QA
> add retries and extra logging for failure to open object

- lib/robots/dor_repo/ocr/start_ocr.rb
Follow on to #1302 to better match what is in fetch-files ... if we hit an error in opening the version, add a bit of delay before retrying again.
CI
> add some delay in retry

- lib/dor/text_extraction/abbyy/file_watcher.rb
- spec/lib/dor/text_extraction/abbyy/file_watcher_spec.rb
- spec/support/abbyy_helper.rb
> remove result.xml files after processing

- lib/dor/text_extraction/abbyy/file_watcher.rb
- lib/dor/text_extraction/abbyy/results.rb
- lib/dor/text_extraction/ocr.rb
- lib/robots/dor_repo/ocr/ocr_workspace_cleanup.rb
- lib/robots/dor_repo/ocr/stage_files.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
1. Trying to learn more about why files/folders do not seem to get deleted sometimes.
2. Code normalization for consistency.
3. Move Result XML file cleanup to the cleanup step when the file is no longer needed (reverting from #1311)
QA and rspec
> add extra logging around deletes/move XML result cleanup

- lib/dor/text_extraction/ocr.rb
- spec/lib/dor/text_extraction/ocr_spec.rb
Fixes #1315 
There may be an issue with the file system sometimes throwing an exception when we try to delete a folder, only for it to succeed on a later attempt (I've seen this happen with a couple times, where the robot completed successfully, but a folder was still there, I tried to delete it on the terminal, it failed, I tried again, and it succeeded).  
Our use of `FileUtils.rm_rf` swallows any errors, so if an error does occur, we won't even know anything has happened and instead the folder will remain.  See https://github.com/ruby/fileutils/issues/57   This PR replaces that call with `FileUtils.rm_r`, which also deletes (non-empty) folders, but WILL thrown an exception if a problem occurs.  This lets us at least catch it and retry.
Note that we now need to verify that the …
> Retry cleanup

- lib/capistrano/tasks/abbyy_watcher_systemd.cap
Did not test, but you may need these explicit prerequisites until we come up with a better solution in dlss-capistrano. Recommend testing before merging!
> Make sure controlmaster is setup and one-time key is generated

- lib/dor/text_extraction/abbyy/results.rb
> update Nokogiri on results to Nokogiri Reader

- Gemfile
- Gemfile.lock
- config/settings.yml
- lib/dor/text_extraction/aws_provider.rb
- lib/dor/text_extraction/robot.rb
- lib/robots/dor_repo/speech_to_text/fetch_files.rb
- lib/robots/dor_repo/speech_to_text/stt_create.rb
- spec/lib/dor/text_extraction/aws_provider_spec.rb
- spec/robots/dor_repo/speech_to_text/fetch_files_spec.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
Fixes #1356 - send an SQS message to kick off speech to text (after files sent to S3)
New specs
> Send sqs message for speech to text create

- config/settings.yml
- lib/robots/dor_repo/speech_to_text/stt_create.rb
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
Follow on from #1367; fixes #1369
- add job_id to HB alert if error occurs
- move whisper options to config
Spec
> Move whisper settings to config; add job id to HB

- config/settings/test.yml
- spec/fixtures/ocr/bb222cc3333.xml.result.xml
- spec/fixtures/ocr/bb222cc3333_abbyy_ticket.xml
- spec/fixtures/ocr/bc123df4567.xml.result.xml
- spec/fixtures/ocr/bc123df4567_abbyy_ticket.xml
- spec/fixtures/ocr/cc333dd4444_abbyy_ticket.xml
- spec/lib/dor/text_extraction/abbyy/results_spec.rb
> abbyy paths are now S:\

- config/settings.yml
- spec/robots/dor_repo/speech_to_text/stt_create_spec.rb
The whisper options for the writer are in a subsection of the options. max_line_width=42 and max_line_count=2 are more realistic than max_line_count=80, but will likely need to be adjusted over time.
unit tests
> Update whisper writer options

- README.md
- config/settings.yml
Bits of cleanup (config space removed and updates to README)
> settings and README updates

- lib/dor/text_extraction/ocr.rb
- lib/dor/text_extraction/speech_to_text.rb
- lib/robots/dor_repo/speech_to_text/update_cocina.rb
> add code comments for clarification

- lib/dor/text_extraction/cocina_updater.rb
Refactor to use patterns from other parts of the code in this class
Spec
> small refactor to make this work like other parts of the code

- spec/lib/dor/text_extraction/file_fetcher_spec.rb
understanding test intentions is helpful.
follow on to https://github.com/sul-dlss/common-accessioning/issues/1421
> Dor::TextExtraction::FileFetcher#write_file_with_retries spec: comment to explain non-obvious spec difference

- config/settings.yml
Fixes #1432 - update whisper options.  only options that deviate from the default are included
~~HOLD pending test on qa~~
Integration test on QA
> add specific whisper params

- config/speech_to_text_filters.yaml
Update filter list based on Andrew's comment in slack: https://stanfordlib.slack.com/archives/C06EVDJV45N/p1736795507546119
> update caption filter list

- .circleci/config.yml
- .rubocop.yml
Keep pace with Ruby bumps
CI, stage
> Bump Ruby to 3.4.1

- .circleci/config.yml
- .codecov.yml
- .rubocop.yml
- README.md
- lib/dor/text_extraction/speech_to_text.rb
- spec/lib/dor/text_extraction/speech_to_text_spec.rb
- spec/spec_helper.rb
> Switch from CodeClimate to CodeCov

- lib/dor/text_extraction/robot.rb
- lib/robots/dor_repo/assembly/base.rb
> Remove misleading usage of `protected` keyword

- Gemfile
- Gemfile.lock
> Unpin ActiveSupport to allow Rails upgrades

- config/settings.yml
- lib/robots/dor_repo/accession/stage.rb
- spec/robots/dor_repo/accession/stage_spec.rb
closes #864
This will perform staging for H3 content. The idea is to use this approach with content from other apps in the future.
Unit, QA
> Adds stage robot.

- lib/dor/text_extraction/abbyy/ticket.rb
- spec/fixtures/ocr/bb222cc3333_abbyy_ticket.xml
- spec/fixtures/ocr/bc123df4567_abbyy_ticket.xml
- spec/fixtures/ocr/cc333dd4444_abbyy_ticket.xml
Fixes #1494 - add some extra parameters to the ABBYY XML ticket
Specs
> add additional parameters to abbyy xml ticket

- lib/robots/dor_repo/accession/stage.rb
- spec/robots/dor_repo/accession/stage_spec.rb
> Adds socket to stage note.

- README.md
- config/settings.yml
- config/settings/test.yml
- lib/dor/text_extraction/file_fetcher.rb
- lib/dor/text_extraction/ocr.rb
- lib/dor/text_extraction/workflow_updater.rb
- lib/robots/dor_repo/accession/end_accession.rb
- lib/robots/dor_repo/accession/start_accession.rb
- lib/robots/dor_repo/assembly/content_metadata_create.rb
- spec/lib/dor/text_extraction/file_fetcher_spec.rb
implement [feedback from review of original PR](https://github.com/sul-dlss/common-accessioning/pull/1509#discussion_r2223623385), fix other related things i noticed in doing that
> Touchups: better lyber-core decoupling, faster tests, readme & comment updates

- lib/robots/dor_repo/accession/start_accession.rb
- spec/robots/dor_repo/accession/start_accession_spec.rb
closes #1538
On a first version, if a file is not found on the file system it will make a request to PresCat and PurlFetcher. However, for version 1, PresCat doesn't know anything about the item and raises an error.
Unit
> Do not get checksums from PresCat or PurlFetcher for version 1

- lib/dor/text_extraction/abbyy/file_watcher.rb
The `abbyy_catchup` utility needs to be able to call `FileWatcher.process_success` and `FileWatcher.process_failure`.
Fixes #1548
Unit tests. Although, perhaps a unit test for the `abbyy_catchup` utility would have caught this...
> Allow public access to methods needed during catchup
